import type { CelebrityRegion } from "./celebrities";

export interface SupplementaryCelebrity {
  month: number;
  day: number;
  name: string;
  profession: string;
  region: CelebrityRegion;
  star: string;
}

export const SUPPLEMENTARY_POOL: SupplementaryCelebrity[] = [
  // ===== JANUARY =====
  { month: 1, day: 1, name: "J. D. Salinger", profession: "Author", region: "Global", star: "The reclusive genius whose Catcher in the Rye gave voice to restless youth." },
  { month: 1, day: 1, name: "E. L. James", profession: "Author", region: "Global", star: "The novelist whose steamy trilogy redefined publishing overnight." },
  { month: 1, day: 2, name: "Isaac Asimov", profession: "Author", region: "Global", star: "The master of science fiction whose Foundation series mapped the future of civilization." },
  { month: 1, day: 2, name: "Christy Turlington", profession: "Model", region: "Hollywood", star: "A supermodel whose timeless beauty and humanitarian spirit transcend fashion." },
  { month: 1, day: 4, name: "Louis Braille", profession: "Inventor", region: "Global", star: "The visionary who gave sight to the blind through a system of raised dots." },
  { month: 1, day: 4, name: "Dave Bautista", profession: "Actor & wrestler", region: "Sports", star: "From the wrestling ring to Hollywood blockbusters, a gentle giant with an artist's soul." },
  { month: 1, day: 5, name: "Robert Duvall", profession: "Actor", region: "Hollywood", star: "A legendary character actor whose quiet intensity steals every scene." },
  { month: 1, day: 6, name: "Eric Clapton", profession: "Guitarist", region: "Global", star: "The slowhand of rock whose guitar wails carry decades of blues and soul." },
  { month: 1, day: 6, name: "Kate McKinnon", profession: "Comedian & actor", region: "Hollywood", star: "A Saturday Night Live legend whose impersonations are eerily brilliant." },
  { month: 1, day: 7, name: "Nicholas Cage", profession: "Actor", region: "Hollywood", star: "An eccentric Oscar winner whose commitment to every role borders on mythic." },
  { month: 1, day: 8, name: "David Bowie", profession: "Singer", region: "Global", star: "The Starman who reinvented himself a dozen times and changed music forever." },
  { month: 1, day: 8, name: "Stephen Hawking", profession: "Physicist", region: "Global", star: "The brilliant cosmologist whose wheelchair became a throne of cosmic wisdom." },
  { month: 1, day: 9, name: "Richard Nixon", profession: "President", region: "Global", star: "The complicated 37th president whose legacy still shapes political discourse." },
  { month: 1, day: 10, name: "Rod Stewart", profession: "Singer", region: "Global", star: "The raspy-voiced rocker whose anthems have filled stadiums for five decades." },
  { month: 1, day: 10, name: "Shahid Kapoor", profession: "Actor", region: "Bollywood", star: "A versatile Bollywood leading man who dances through drama and action with equal ease." },
  { month: 1, day: 11, name: "Geoffrey Chaucer", profession: "Poet", region: "Global", star: "The father of English literature whose Canterbury Tales became the roadmap of storytelling." },
  { month: 1, day: 11, name: "Mary J. Blige", profession: "Singer", region: "Global", star: "The Queen of Hip-Hop Soul whose raw vocals carry a generation's pain and triumph." },
  { month: 1, day: 12, name: "Jack London", profession: "Author", region: "Global", star: "The adventure writer who turned the frozen wild into enduring literary fire." },
  { month: 1, day: 12, name: "Nadiem Makarim", profession: "Entrepreneur", region: "Global", star: "The Gojek founder who built a tech empire from the streets of Jakarta." },
  { month: 1, day: 15, name: "Martin Luther King Jr.", profession: "Civil rights leader", region: "Global", star: "The dreamer whose vision of equality transformed a nation and inspired the world." },
  { month: 1, day: 15, name: "Drew Barrymore", profession: "Actor", region: "Hollywood", star: "From child star to Hollywood sweetheart, a survivor whose warmth is irresistible." },
  { month: 1, day: 17, name: "Benjamin Franklin", profession: "Polymath", region: "Global", star: "A founding father whose lightning experiments and wisdom light the way to this day." },
  { month: 1, day: 17, name: "Zooey Deschanel", profession: "Actor & singer", region: "Hollywood", star: "A quirky Hollywood darling whose whimsy and voice brighten every frame." },
  { month: 1, day: 19, name: "Janis Joplin", profession: "Singer", region: "Global", star: "The raw soul of rock whose voice exploded with bluesy passion from every stage." },
  { month: 1, day: 20, name: "Denzel Washington", profession: "Actor & director", region: "Hollywood", star: "An acting titan whose moral gravity anchors every film he graces." },
  { month: 1, day: 21, name: "Sting", profession: "Singer", region: "Global", star: "The Police frontman whose intellectual pop and solo reinvention spanned decades." },
  { month: 1, day: 21, name: "Hedi Slimane", profession: "Fashion designer", region: "Global", star: "The enigmatic designer who reshaped luxury fashion with rock-and-roll minimalism." },
  { month: 1, day: 22, name: "Lord Byron", profession: "Poet", region: "Global", star: "The flamboyant Romantic poet whose scandalous life was as epic as his verse." },
  { month: 1, day: 23, name: "Chesney Hawkes", profession: "Singer", region: "Global", star: "The one-hit wonder whose anthem 'The One and Only' became a generation's battle cry." },
  { month: 1, day: 24, name: "Aaron Neville", profession: "Singer", region: "Global", star: "A voice like honey and gravel that made New Orleans soul shine." },
  { month: 1, day: 24, name: "Shreya Ghoshal", profession: "Singer", region: "Bollywood", star: "India's nightingale whose melody has graced a thousand Bollywood love stories." },
  { month: 1, day: 25, name: "Alicia Keys", profession: "Singer", region: "Global", star: "The piano prodigy whose neo-soul anthems defined modern R&B." },
  { month: 1, day: 26, name: "Douglas MacArthur", profession: "General", region: "Global", star: "A five-star general whose wartime leadership shaped the Pacific theatre." },
  { month: 1, day: 26, name: "Lata Mangeshkar", profession: "Singer", region: "Bollywood", star: "The Nightingale of India, whose voice is woven into the soul of a billion hearts." },
  { month: 1, day: 28, name: "Alan Alda", profession: "Actor", region: "Hollywood", star: "The beloved Hawkeye Pierce who brought humor and humanity to the small screen." },
  { month: 1, day: 29, name: "Oprah Winfrey", profession: "Media mogul", region: "Global", star: "A self-made icon whose empathy and influence redefined television and philanthropy." },
  { month: 1, day: 30, name: "Franklin D. Roosevelt", profession: "President", region: "Global", star: "The New Deal architect who steered America through Depression and war." },
  { month: 1, day: 30, name: "Gene Hackman", profession: "Actor", region: "Hollywood", star: "A gritty two-time Oscar winner who retired from Hollywood on his own terms." },
  { month: 1, day: 31, name: "Ernst Stavro Blofeld", profession: "Fictional villain", region: "Hollywood", star: "The iconic Bond villain whose legacy looms over espionage cinema." },
  { month: 1, day: 31, name: "Portia de Rossi", profession: "Actor", region: "Hollywood", star: "A graceful actress and advocate whose elegance shines on screen and off." },

  // ===== FEBRUARY =====
  { month: 2, day: 5, name: "John Callahan", profession: "Cartoonist", region: "Global", star: "The darkly comic artist who proved humor can bloom even from the darkest soil." },
  { month: 2, day: 1, name: "Lisa Marie Presley", profession: "Singer", region: "Global", star: "The daughter of the King who carried the weight of a dynasty with grace and music." },
  { month: 2, day: 3, name: "Norman Mailer", profession: "Author", region: "Global", star: "A literary provocateur whose nonfiction and novels rewrote American letters." },
  { month: 2, day: 3, name: "Isla Fisher", profession: "Actor", region: "Hollywood", star: "A Scottish-born Australian actress whose comedic sparkle lights up every ensemble." },
  { month: 2, day: 5, name: "Hank Aaron", profession: "Baseball player", region: "Sports", star: "The Home Run King whose grace under pressure broke baseball's most hallowed record." },
  { month: 2, day: 5, name: "Barack Obama", profession: "President", region: "Global", star: "The 44th president whose hope-fueled campaign inspired a generation worldwide." },
  { month: 2, day: 6, name: "Bob Marley", profession: "Singer", region: "Global", star: "The reggae legend whose music became the universal anthem of peace and love." },
  { month: 2, day: 6, name: "Ronald Reagan", profession: "President & actor", region: "Hollywood", star: "From Hollywood leading man to the White House, the Great Communicator." },
  { month: 2, day: 7, name: "Charles Dickens", profession: "Author", region: "Global", star: "The Victorian novelist whose characters still live and breathe in our collective imagination." },
  { month: 2, day: 7, name: "Ashton Kutcher", profession: "Actor", region: "Hollywood", star: "A prankster turned tech investor who brought youthful energy to Hollywood." },
  { month: 2, day: 8, name: "James Dean", profession: "Actor", region: "Hollywood", star: "The rebel without a cause whose brief brilliance became a timeless icon." },
  { month: 2, day: 8, name: "John Williams", profession: "Composer", region: "Hollywood", star: "The maestro behind Star Wars, E.T., and Jaws whose music defines cinema." },
  { month: 2, day: 9, name: "Michael B. Jordan", profession: "Actor", region: "Hollywood", star: "A powerhouse performer who brought depth and fire to Killmonger and Creed." },
  { month: 2, day: 9, name: "Mia Farrow", profession: "Actor", region: "Hollywood", star: "An ethereal screen presence whose work with Hitchcock and Polanski defined an era." },
  { month: 2, day: 10, name: "Boris Becker", profession: "Tennis player", region: "Sports", star: "The German prodigy whose youthful Wimbledon triumph electrified the tennis world." },
  { month: 2, day: 10, name: "Emma Roberts", profession: "Actor", region: "Hollywood", star: "A genre queen whose sharp performances keep audiences on the edge of their seats." },
  { month: 2, day: 12, name: "Abraham Lincoln", profession: "President", region: "Global", star: "The rail-splitter who held a fractured nation together and freed a people." },
  { month: 2, day: 12, name: "Judi Dench", profession: "Actor", region: "Global", star: "A national treasure whose regal performances span Shakespeare to M." },
  { month: 2, day: 13, name: "Tina Turner", profession: "Singer", region: "Global", star: "The Queen of Rock and Roll whose comeback story is the stuff of legend." },
  { month: 2, day: 13, name: "Randy Moss", profession: "Football player", region: "Sports", star: "The most electrifying receiver in NFL history whose talent defied gravity." },
  { month: 2, day: 14, name: "Florence Nightingale", profession: "Nurse", region: "Global", star: "The founder of modern nursing whose lamp became a symbol of healing worldwide." },
  { month: 2, day: 14, name: "Frederick Douglass", profession: "Abolitionist", region: "Global", star: "An escaped slave whose oratory and writings became weapons against injustice." },
  { month: 2, day: 15, name: "Galileo Galilei", profession: "Astronomer", region: "Global", star: "The father of modern science who dared to tell the world the Earth moves." },
  { month: 2, day: 15, name: "Amber Valletta", profession: "Model & actor", region: "Hollywood", star: "A supermodel-turned-actress whose chameleon beauty spans decades of style." },
  { month: 2, day: 16, name: "Sonny Bono", profession: "Singer & politician", region: "Global", star: "Half of pop's most colorful duo, who found a second act in City Hall." },
  { month: 2, day: 16, name: "Elizabeth Olsen", profession: "Actor", region: "Hollywood", star: "The Scarlet Witch actress who brings depth and vulnerability to the Marvel Universe." },
  { month: 2, day: 18, name: "John Travolta", profession: "Actor", region: "Hollywood", star: "The Grease and Pulp Fiction star whose charisma and dance moves defined eras." },
  { month: 2, day: 19, name: "Nicolaus Copernicus", profession: "Astronomer", region: "Global", star: "The quiet revolutionary who moved the Earth from the center of everything." },
  { month: 2, day: 19, name: "Millie Bobby Brown", profession: "Actor", region: "Hollywood", star: "A young powerhouse who became the face of a generation's imagination." },
  { month: 2, day: 20, name: "Rihanna", profession: "Singer & entrepreneur", region: "Global", star: "A Barbadian powerhouse who turned pop stardom into a billion-dollar empire." },
  { month: 2, day: 22, name: "George Washington", profession: "President", region: "Global", star: "The indispensable founding father who led a revolution and set the precedent for democracy." },
  { month: 2, day: 22, name: "Drew Pinsky", profession: "Physician & TV host", region: "Global", star: "The celebrity doctor whose radio and TV presence made medicine accessible to millions." },
  { month: 2, day: 23, name: "George Frideric Handel", profession: "Composer", region: "Global", star: "The Baroque master whose Messiah is performed every year and echoes through eternity." },
  { month: 2, day: 24, name: "Steve Jobs", profession: "Entrepreneur", region: "Global", star: "The visionary who put a dent in the universe from a garage in Cupertino." },
  { month: 2, day: 25, name: "Enzo Ferrari", profession: "Entrepreneur", region: "Global", star: "The man whose prancing horse became the world's most iconic speed symbol." },
  { month: 2, day: 25, name: "Sean Astin", profession: "Actor", region: "Hollywood", star: "The hobbit, the Goonie, and the Rudy whose earnest charm warms every role." },
  { month: 2, day: 27, name: "John Steinbeck", profession: "Author", region: "Global", star: "The Nobel laureate whose novels of Dust Bowl America remain painfully relevant." },
  { month: 2, day: 27, name: "Elizabeth Taylor", profession: "Actor", region: "Hollywood", star: "A violet-eyed legend whose beauty and tumultuous life made Hollywood history." },
  { month: 2, day: 28, name: "Vincent van Gogh", profession: "Painter", region: "Global", star: "The tormented genius whose starry nights and sunflowers illuminate the world." },
  { month: 2, day: 28, name: "Ilaiyaraaja", profession: "Composer", region: "Bollywood", star: "The maestro who brought symphonic grandeur to South Indian cinema and beyond." },

  // ===== MARCH =====
  { month: 3, day: 1, name: "Frédéric Chopin", profession: "Composer", region: "Global", star: "The poet of the piano whose nocturnes still make the world pause and listen." },
  { month: 3, day: 1, name: "Ron Howard", profession: "Director & actor", region: "Hollywood", star: "From Opie to Oscar-winning director, a Hollywood dynasty built on storytelling." },
  { month: 3, day: 2, name: "Desi Arnaz", profession: "Actor & musician", region: "Hollywood", star: "The Cuban bandleader who revolutionized television with I Love Lucy." },
  { month: 3, day: 2, name: "Jon Bon Jovi", profession: "Singer", region: "Global", star: "The New Jersey rocker whose anthems turned arena rock into a way of life." },
  { month: 3, day: 5, name: "Eva Mendes", profession: "Actor", region: "Hollywood", star: "A Hollywood leading lady whose poise and entrepreneurial spirit make her a modern icon." },
  { month: 3, day: 4, name: "Antonio Banderas", profession: "Actor", region: "Hollywood", star: "A Spanish charmer who brought Latin heat to Hollywood's biggest stages." },
  { month: 3, day: 5, name: "Eva Mendes", profession: "Actor", region: "Hollywood", star: "A Cuban-American beauty whose presence lights up comedy and drama alike." },
  { month: 3, day: 6, name: "Kiri Te Kanawa", profession: "Soprano", region: "Global", star: "A voice of pure gold that made opera a household wonder." },
  { month: 3, day: 6, name: "Shaquille O'Neal", profession: "Basketball player", region: "Sports", star: "The most dominant force in basketball history, a gentle giant off the court." },
  { month: 3, day: 7, name: "Rachel Weisz", profession: "Actor", region: "Hollywood", star: "A British powerhouse whose intelligence and depth elevate every performance." },
  { month: 3, day: 8, name: "Marlon Brando", profession: "Actor", region: "Hollywood", star: "The godfather of method acting whose raw power redefined screen performance." },
  { month: 3, day: 9, name: "Bobby Fischer", profession: "Chess champion", region: "Global", star: "The chess prodigy whose Cold War showdown became a global spectacle." },
  { month: 3, day: 10, name: "Shinzo Abe", profession: "Prime Minister", region: "Global", star: "Japan's longest-serving prime minister whose Abenomics reshaped economic debate." },
  { month: 3, day: 10, name: "Carrie Underwood", profession: "Singer", region: "Global", star: "The American Idol champion who became country music's reigning queen." },
  { month: 3, day: 11, name: "Rupert Murdoch", profession: "Media mogul", region: "Global", star: "The titan of media whose empire reshaped news on every continent." },
  { month: 3, day: 11, name: "Thandiwe Newton", profession: "Actor", region: "Hollywood", star: "A British-Zimbabwean actress whose fierce grace powers every role she inhabits." },
  { month: 3, day: 12, name: "Andrew Lloyd Webber", profession: "Composer", region: "Global", star: "The musical theatre genius whose Cats and Phantom stunned the world." },
  { month: 3, day: 13, name: "Adam Clayton", profession: "Musician", region: "Global", star: "U2's bassist whose steady groove anchors one of rock's greatest bands." },
  { month: 3, day: 14, name: "Stephen Curry", profession: "Basketball player", region: "Sports", star: "The three-point king who changed how basketball is played forever." },
  { month: 3, day: 15, name: "Ruth Bader Ginsburg", profession: "Supreme Court justice", region: "Global", star: "The Notorious RBG who fought for gender equality from the nation's highest bench." },
  { month: 3, day: 16, name: "James Madison", profession: "President", region: "Global", star: "The father of the Constitution whose quiet brilliance shaped American democracy." },
  { month: 3, day: 17, name: "Mikhail Gorbachev", profession: "Statesman", region: "Global", star: "The reformer who ended the Cold War and dared to open a closed world." },
  { month: 3, day: 17, name: "Stormy Daniels", profession: "Author", region: "Global", star: "An author and public figure whose story sparked a national reckoning." },
  { month: 3, day: 19, name: "Bruce Willis", profession: "Actor", region: "Hollywood", star: "The wisecracking action hero who made Die Hard the gold standard for the genre." },
  { month: 3, day: 20, name: "Wolfgang Amadeus Mozart", profession: "Composer", region: "Global", star: "The divine child of music whose compositions still feel impossibly perfect." },
  { month: 3, day: 20, name: "Halston", profession: "Fashion designer", region: "Hollywood", star: "The Studio 54-era designer whose minimalist glamour defined American fashion." },
  { month: 3, day: 21, name: "Johann Sebastian Bach", profession: "Composer", region: "Global", star: "The cathedral builder of music whose fugues still make the heavens listen." },
  { month: 3, day: 21, name: "Matthew Broderick", profession: "Actor", region: "Hollywood", star: "The charming WarGames star whose Ferris Bueller remains the ultimate truant hero." },
  { month: 3, day: 22, name: "Reese Witherspoon", profession: "Actor & producer", region: "Hollywood", star: "An Oscar winner turned media mogul who champions women's stories at every turn." },
  { month: 3, day: 24, name: "Steve McQueen", profession: "Actor", region: "Hollywood", star: "The King of Cool whose motorbike roles and detached charisma defined 1960s cinema." },
  { month: 3, day: 25, name: "Aretha Franklin", profession: "Singer", region: "Global", star: "The Queen of Soul whose Respect became the anthem of empowerment." },
  { month: 3, day: 25, name: "Elton John", profession: "Singer", region: "Global", star: "The Rocket Man whose piano pyrotechnics and flamboyance filled stadiums for decades." },
  { month: 3, day: 27, name: "Ludwig van Beethoven", profession: "Composer", region: "Global", star: "The deaf Titan who proved music lives beyond silence and adversity." },
  { month: 3, day: 28, name: "Reba McEntire", profession: "Singer & actor", region: "Global", star: "The country queen whose voice and resilience made her a beloved American icon." },
  { month: 3, day: 29, name: "John Major", profession: "Prime Minister", region: "Global", star: "The quiet Conservative who steered Britain through turbulent economic waters." },
  { month: 3, day: 31, name: "César Chávez", profession: "Activist", region: "Global", star: "A farmworker's champion whose nonviolent protests gave a voice to the voiceless." },
  { month: 3, day: 31, name: "Ewan McGregor", profession: "Actor", region: "Hollywood", star: "From Jedi Knight to motorcycle adventurer, a Scotsman who brings heart to every journey." },

  // ===== APRIL =====
  { month: 4, day: 1, name: "Debbie Reynolds", profession: "Actor & singer", region: "Hollywood", star: "The Singin' in the Rain star whose effervescent talent spanned five decades." },
  { month: 4, day: 1, name: "Asa Butterfield", profession: "Actor", region: "Hollywood", star: "A young British talent who brought soul to sci-fi and coming-of-age stories." },
  { month: 4, day: 2, name: "Marvin Gaye", profession: "Singer", region: "Global", star: "The Prince of Soul whose What's Going On became the conscience of a generation." },
  { month: 4, day: 2, name: "Lindsey Vonn", profession: "Ski racer", region: "Sports", star: "The most decorated American ski racer whose speed and courage defined alpine legend." },
  { month: 4, day: 4, name: "Robert Downey Jr.", profession: "Actor", region: "Hollywood", star: "The Iron Man of Hollywood whose epic comeback story rivals any superhero's." },
  { month: 4, day: 5, name: "Bette Davis", profession: "Actor", region: "Hollywood", star: "A fierce Oscar legend who owned every role with eyes that saw through pretense." },
  { month: 4, day: 6, name: "Ricky Gervais", profession: "Comedian & actor", region: "Global", star: "The sharp-tongued British comic whose Golden Globe monologues became events." },
  { month: 4, day: 7, name: "Billie Holiday", profession: "Singer", region: "Global", star: "Lady Day whose voice carried the sorrow and beauty of the human experience." },
  { month: 4, day: 9, name: "J. William Fulbright", profession: "Senator", region: "Global", star: "The senator whose scholarship program opened the world's minds to each other." },
  { month: 4, day: 9, name: "Dennis Quaid", profession: "Actor", region: "Hollywood", star: "A rugged everyman whose affable charm brings warmth to thrillers and dramas." },
  { month: 4, day: 10, name: "Steven Spielberg", profession: "Director", region: "Hollywood", star: "The blockbuster king whose imagination turned sharks, aliens, and history into myth." },
  { month: 4, day: 11, name: "Ethel Kennedy", profession: "Humanitarian", region: "Global", star: "A tireless advocate for social justice who carried the Kennedy legacy with grace." },
  { month: 4, day: 11, name: "Mark Ruffalo", profession: "Actor", region: "Hollywood", star: "The Hulk with a heart, a passionate advocate who brings humanity to blockbusters." },
  { month: 4, day: 13, name: "Al Green", profession: "Singer", region: "Global", star: "The soul singer whose silky voice made Let's Stay Together eternal." },
  { month: 4, day: 14, name: "Sarah Michelle Gellar", profession: "Actor", region: "Hollywood", star: "The Buffy legend who proved a small-screen slayer could become a cultural icon." },
  { month: 4, day: 15, name: "Leonardo da Vinci", profession: "Artist & inventor", region: "Global", star: "The ultimate Renaissance man whose paintings and blueprints still defy explanation." },
  { month: 4, day: 15, name: "Emma Thompson", profession: "Actor & screenwriter", region: "Hollywood", star: "A British treasure whose wit and warmth shine in every role she inhabits." },
  { month: 4, day: 16, name: "Charlie Chaplin", profession: "Comedian & filmmaker", region: "Hollywood", star: "The Little Tramp who made silent cinema the world's universal language." },
  { month: 4, day: 17, name: "Geena Davis", profession: "Actor", region: "Hollywood", star: "An Oscar-winning actress and archery champion whose advocacy changed Hollywood." },
  { month: 4, day: 18, name: "Edvard Grieg", profession: "Composer", region: "Global", star: "The Norwegian composer whose Peer Gynt suites sound like fjords in music." },
  { month: 4, day: 19, name: "Mariah Carey", profession: "Singer", region: "Global", star: "The Songbird Supreme whose five-octave voice and holiday anthem reign supreme." },
  { month: 4, day: 20, name: "Jessica Lange", profession: "Actor", region: "Hollywood", star: "A two-time Oscar winner whose fearless performances span blockbuster and indie." },
  { month: 4, day: 24, name: "Shirley MacLaine", profession: "Actor", region: "Hollywood", star: "An Oscar legend whose adventurous spirit and openness define a life well-lived." },
  { month: 4, day: 25, name: "Ella Fitzgerald", profession: "Singer", region: "Global", star: "The First Lady of Song whose pure voice and scatting redefined jazz vocals." },
  { month: 4, day: 26, name: "Jay Leno", profession: "Comedian & TV host", region: "Hollywood", star: "The chin that hosted The Tonight Show for two decades with everyman charm." },
  { month: 4, day: 27, name: "Ulysses S. Grant", profession: "General & president", region: "Global", star: "The Union's savior turned president whose memoirs are a masterpiece of American prose." },
  { month: 4, day: 27, name: "Sandra Dee", profession: "Actor", region: "Hollywood", star: "The golden girl of 1960s cinema whose sweet persona became a cultural touchstone." },
  { month: 4, day: 28, name: "Saddam Hussein", profession: "Dictator", region: "Global", star: "A brutal dictator whose reign of terror scarred the Middle East for decades." },
  { month: 4, day: 28, name: "Penélope Cruz", profession: "Actor", region: "Hollywood", star: "A Spanish jewel whose fiery performances lit up both European and Hollywood cinema." },
  { month: 4, day: 29, name: "Uma Thurman", profession: "Actor", region: "Hollywood", star: "A Tarantino muse whose lethal elegance and revenge fantasy defined cult cinema." },
  { month: 4, day: 30, name: "Phil Collins", profession: "Singer", region: "Global", star: "The Genesis frontman whose In the Air Tonight drum fill is pop culture's heartbeat." },

  // ===== MAY =====
  { month: 5, day: 1, name: "Lily Allen", profession: "Singer", region: "Global", star: "The cheeky British pop star whose witty lyrics tackled celebrity culture head-on." },
  { month: 5, day: 1, name: "David Beckham", profession: "Footballer", region: "Sports", star: "The midfielder whose free kicks and fashion sense made him a global brand." },
  { month: 5, day: 2, name: "Federico Fellini", profession: "Director", region: "Global", star: "The Italian maestro whose dreamlike films reinvented cinematic storytelling." },
  { month: 5, day: 3, name: "Niccolò Machiavelli", profession: "Philosopher", region: "Global", star: "The Florentine thinker whose political strategies still echo through power corridors." },
  { month: 5, day: 3, name: "Mary Astor", profession: "Actor", region: "Hollywood", star: "An Oscar winner whose Maltese Falcon performance set the noir standard." },
  { month: 5, day: 4, name: "Rabindranath Tagore", profession: "Poet", region: "Global", star: "The Bengali polymath whose Gitanjali won the Nobel and enriched world literature." },
  { month: 5, day: 4, name: "Will Arnett", profession: "Actor", region: "Hollywood", star: "The deep-voiced comic genius behind Arrested Development and BoJack Horseman." },
  { month: 5, day: 5, name: "Karl Marx", profession: "Philosopher", region: "Global", star: "The thinker whose theories reshaped politics and economics on every continent." },
  { month: 5, day: 5, name: "Tina Fey", profession: "Comedian & writer", region: "Hollywood", star: "The comedy powerhouse behind 30 Rock and Mean Girls who made women funnier." },
  { month: 5, day: 6, name: "Sigourney Weaver", profession: "Actor", region: "Hollywood", star: "The original sci-fi action heroine who faced aliens and dragons with equal steel." },
  { month: 5, day: 7, name: "Johannes Brahms", profession: "Composer", region: "Global", star: "The Romantic master whose symphonies carry both thunder and tender whispers." },
  { month: 5, day: 7, name: "Ivanka Trump", profession: "Businesswoman", region: "Global", star: "A businesswoman and former First Daughter whose brand walks the line of public fascination." },
  { month: 5, day: 8, name: "Harry S. Truman", profession: "President", region: "Global", star: "The haberdasher turned president whose decisive choices shaped the modern world." },
  { month: 5, day: 9, name: "Billy Joel", profession: "Singer", region: "Global", star: "The Piano Man whose ballads became the soundtrack of American life." },
  { month: 5, day: 10, name: "Bono", profession: "Singer", region: "Global", star: "The U2 frontman who turned rock stardom into global activism on an epic scale." },
  { month: 5, day: 10, name: "Sid Vicious", profession: "Musician", region: "Global", star: "The punk icon whose chaotic life and death embodied the Sex Pistols' dangerous spirit." },
  { month: 5, day: 11, name: "Frida Kahlo", profession: "Painter", region: "Global", star: "The unflinching artist who turned pain and identity into vivid, unforgettable self-portraits." },
  { month: 5, day: 11, name: "Salvador Dalí", profession: "Painter", region: "Global", star: "The surrealist wizard whose melting clocks and mustache became art's most famous image." },
  { month: 5, day: 13, name: "Stevie Wonder", profession: "Singer", region: "Global", star: "The musical genius whose blind eyes saw deeper into music than anyone else." },
  { month: 5, day: 14, name: "Tony Hawk", profession: "Skateboarder", region: "Sports", star: "The pro skater who turned counterculture into an Olympic sport." },
  { month: 5, day: 16, name: "Henry Fonda", profession: "Actor", region: "Hollywood", star: "The quintessential American hero of 12 Angry Men and On Golden Pond." },
  { month: 5, day: 17, name: "Queen Victoria", profession: "Monarch", region: "Global", star: "The queen whose reign gave an era its name and the world its longest-lasting empire." },
  { month: 5, day: 18, name: "Frank Capra", profession: "Director", region: "Hollywood", star: "The director of It's a Wonderful Life who believed in the goodness of ordinary people." },
  { month: 5, day: 19, name: "Pete Townshend", profession: "Musician", region: "Global", star: "The Who's windmill guitarist who turned rock operas into high art." },
  { month: 5, day: 20, name: "Honoré de Balzac", profession: "Author", region: "Global", star: "The French novelist whose Human Comedy mapped an entire society in fiction." },
  { month: 5, day: 20, name: "Tony Goldwyn", profession: "Actor & director", region: "Hollywood", star: "A versatile performer whose measured authority graces both screen and stage." },
  { month: 5, day: 22, name: "Richard Wagner", profession: "Composer", region: "Global", star: "The controversial genius whose operas pushed music and drama to epic new heights." },
  { month: 5, day: 22, name: "Naomi Campbell", profession: "Model", region: "Global", star: "The British supermodel whose fierce runway presence broke barriers and redefined beauty." },
  { month: 5, day: 23, name: "Carrie Fisher", profession: "Actor & writer", region: "Hollywood", star: "Princess Leia off-screen and on, a razor-sharp wit who turned personal chaos into brilliant writing." },
  { month: 5, day: 24, name: "Bob Dylan", profession: "Singer & songwriter", region: "Global", star: "The Nobel laureate whose words gave the protest movement its voice and poetry." },
  { month: 5, day: 25, name: "Ian McKellen", profession: "Actor", region: "Global", star: "Gandalf and Magneto, a theatrical knight whose range spans Shakespeare to Middle-earth." },
  { month: 5, day: 25, name: "Priscilla Presley", profession: "Actor", region: "Hollywood", star: "The woman who kept Elvis's legacy alive and found her own spotlight in Dallas." },
  { month: 5, day: 26, name: "Al Pacino", profession: "Actor", region: "Hollywood", star: "The godfather of screen intensity whose whisper-to-scream range is unmatched." },
  { month: 5, day: 27, name: "Alvin Ailey", profession: "Choreographer", region: "Global", star: "The visionary whose dance company brought African-American experience to the stage." },
  { month: 5, day: 28, name: "Ian Fleming", profession: "Author", region: "Global", star: "The man who created James Bond and turned spy fiction into a global obsession." },
  { month: 5, day: 28, name: "Kylie Minogue", profession: "Singer", region: "Global", star: "The Australian pop princess who turned Can't Get You Out of My Head into a worldwide earworm." },
  { month: 5, day: 29, name: "John F. Kennedy", profession: "President", region: "Global", star: "The young president whose Camelot ideal still shines in American memory." },
  { month: 5, day: 29, name: "Bob Hope", profession: "Comedian", region: "Hollywood", star: "The USO entertainer who brought laughter to troops across five decades of wars." },
  { month: 5, day: 30, name: "Ingmar Bergman", profession: "Director", region: "Global", star: "The Swedish master whose existential films probed the deepest questions of the soul." },
  { month: 5, day: 31, name: "Walt Whitman", profession: "Poet", region: "Global", star: "The poet of democracy whose Leaves of Grass is America's literary heartbeat." },
  { month: 5, day: 31, name: "Clint Eastwood", profession: "Actor & director", region: "Hollywood", star: "The man with no name who became the most enduring cowboy of American cinema." },

  // ===== JUNE =====
  { month: 6, day: 1, name: "Marilyn Monroe", profession: "Actor", region: "Hollywood", star: "The blonde bombshell whose luminous vulnerability made her the most iconic star ever." },
  { month: 6, day: 1, name: "Alan Bates", profession: "Actor", region: "Global", star: "A British New Wave legend whose raw performances changed acting on both stage and screen." },
  { month: 6, day: 2, name: "Johnny Cash", profession: "Singer", region: "Global", star: "The Man in Black whose deep voice carried the weight of America's heartland." },
  { month: 6, day: 2, name: "Catherine Zeta-Jones", profession: "Actor", region: "Hollywood", star: "A Welsh beauty whose Oscar-winning performances shimmer with elegance and steel." },
  { month: 6, day: 4, name: "Angelina Jolie", profession: "Actor & humanitarian", region: "Hollywood", star: "An Oscar-winning actress turned global humanitarian whose passion burns on every front." },
  { month: 6, day: 5, name: "Pablo Picasso", profession: "Painter", region: "Global", star: "The artist who shattered perspective and rebuilt it into Cubism, changing art forever." },
  { month: 6, day: 5, name: "Mark Wahlberg", profession: "Actor", region: "Hollywood", star: "From Marky Mark to leading man, a Bostonian whose reinvention is pure determination." },
  { month: 6, day: 6, name: "Robert Fulghum", profession: "Author", region: "Global", star: "The minister-turned-writer whose All I Really Need to Know I Learned in Kindergarten became a mantra." },
  { month: 6, day: 7, name: "Liam Neeson", profession: "Actor", region: "Hollywood", star: "The Northern Irish giant whose quiet intensity and particular set of skills define modern action." },
  { month: 6, day: 8, name: "Barbara Bush", profession: "First Lady", region: "Global", star: "The beloved First Lady whose white hair and warm wit made her America's grandmother." },
  { month: 6, day: 8, name: "Keenan Thompson", profession: "Comedian", region: "Hollywood", star: "Saturday Night Live's longest-tenured cast member, a comedy institution unto himself." },
  { month: 6, day: 9, name: "Robert F. Kennedy", profession: "Senator", region: "Global", star: "The Kennedy brother whose unfinished campaign promised a more just America." },
  { month: 6, day: 9, name: "Michael J. Fox", profession: "Actor", region: "Hollywood", star: "The Back to the Future hero whose battle with Parkinson's made him a real-life champion." },
  { month: 6, day: 10, name: "Lionel Richie", profession: "Singer", region: "Global", star: "The smooth crooner whose Hello became the soundtrack of romantic yearning." },
  { month: 6, day: 10, name: "Judy Garland", profession: "Singer & actor", region: "Hollywood", star: "Over the rainbow and beyond, a voice that still makes the world dream." },
  { month: 6, day: 11, name: "Hugh Laurie", profession: "Actor", region: "Hollywood", star: "A British comedy genius who became TV's most brilliant and grumpy doctor." },
  { month: 6, day: 12, name: "George H. W. Bush", profession: "President", region: "Global", star: "The 41st president whose quiet diplomacy ended the Cold War without a shot fired." },
  { month: 6, day: 12, name: "Adriana Lima", profession: "Model", region: "Hollywood", star: "The longest-serving Victoria's Secret Angel whose Brazilian beauty became a global standard." },
  { month: 6, day: 14, name: "Steffi Graf", profession: "Tennis player", region: "Sports", star: "The German tennis legend whose Golden Slam remains the most remarkable feat in the sport." },
  { month: 6, day: 14, name: "Chevy Chase", profession: "Comedian & actor", region: "Hollywood", star: "The original SNL weekend anchor whose physical comedy made Griswold a household name." },
  { month: 6, day: 15, name: "Helen Hunt", profession: "Actor", region: "Hollywood", star: "An Oscar-winning actress whose natural warmth makes every performance feel effortless." },
  { month: 6, day: 15, name: "Ice Cube", profession: "Rapper & actor", region: "Hollywood", star: "From NWA to family comedies, a rapper-turned-mogul who keeps reinventing the hustle." },
  { month: 6, day: 16, name: "Tupac Shakur", profession: "Rapper", region: "Global", star: "The poet of hip-hop whose music and message outlived his tragically short life." },
  { month: 6, day: 17, name: "Joe Pesci", profession: "Actor", region: "Hollywood", star: "The pint-sized powerhouse whose volcanic rants made Goodfellas and Home Alone legendary." },
  { month: 6, day: 18, name: "Paul McCartney", profession: "Singer", region: "Global", star: "The Beatle who wrote Yesterday and never stopped creating magic across six decades." },
  { month: 6, day: 18, name: "Isabella Rossellini", profession: "Actor & model", region: "Hollywood", star: "An Italian-Swedish beauty whose graceful aging and film work defy time." },
  { month: 6, day: 19, name: "Macklemore", profession: "Rapper", region: "Global", star: "The Seattle MC whose thrift shop swagger and conscious lyrics break conventions." },
  { month: 6, day: 20, name: "Lionel Messi", profession: "Footballer", region: "Sports", star: "The little magician whose genius with a ball made him the greatest footballer alive." },
  { month: 6, day: 20, name: "Martin Landau", profession: "Actor", region: "Hollywood", star: "An Oscar-winning character actor whose Mission Impossible and Ed Wood work spanned decades." },
  { month: 6, day: 21, name: "Ray Bradbury", profession: "Author", region: "Global", star: "The poet of Fahrenheit 451 and Martian Chronicles whose imagination burned with warnings." },
  { month: 6, day: 21, name: "Prince William", profession: "Royal", region: "Global", star: "The heir to the British throne who modernized the monarchy with quiet grace." },
  { month: 6, day: 22, name: "Kris Kristofferson", profession: "Singer & actor", region: "Global", star: "The poet-country star whose Me and Bobby McGee and A Star Is Born bridged music and film." },
  { month: 6, day: 23, name: "Joss Whedon", profession: "Screenwriter & director", region: "Hollywood", star: "The Buffy creator and Avengers director whose witty dialogue defined a generation." },
  { month: 6, day: 25, name: "George Michael", profession: "Singer", region: "Global", star: "The Wham! frontman turned solo icon whose Faith and vocal brilliance endure." },
  { month: 6, day: 25, name: "Ricardo Montalbán", profession: "Actor", region: "Hollywood", star: "The Star Trek villain whose velvety voice and charisma transcended camp into legend." },
  { month: 6, day: 26, name: "Arianna Huffington", profession: "Entrepreneur", region: "Global", star: "The media mogul who built HuffPost into a digital empire and champions sleep." },
  { month: 6, day: 28, name: "Kellie Pickler", profession: "Singer", region: "Global", star: "The American Idol favorite whose country charm won hearts from small-town roots." },
  { month: 6, day: 29, name: "Calvin Coolidge", profession: "President", region: "Global", star: "Silent Cal, the taciturn president whose restraint defined the Roaring Twenties." },
  { month: 6, day: 30, name: "Michael Phelps", profession: "Swimmer", region: "Sports", star: "The most decorated Olympian in history, whose pool dominance redefined athletic greatness." },

  // ===== JULY =====
  { month: 7, day: 1, name: "Lionel Barrymore", profession: "Actor", region: "Hollywood", star: "The Barrymore dynasty patriarch whose Scrooge and villain roles became legend." },
  { month: 7, day: 1, name: "Missy Elliott", profession: "Rapper & producer", region: "Global", star: "The hip-hop innovator whose beats and verses changed the genre's creative landscape." },
  { month: 7, day: 2, name: "Prince Amedeo of Savoy", profession: "Royalty", region: "Global", star: "A royal whose adventurous life embodied the romance of 20th-century European aristocracy." },
  { month: 7, day: 2, name: "Lindsay Lohan", profession: "Actor", region: "Hollywood", star: "From child star to comeback queen, a redhead whose talent keeps fighting through headlines." },
  { month: 7, day: 4, name: "Neil Simon", profession: "Playwright", region: "Hollywood", star: "The most commercially successful playwright in American history, whose comedies still pack houses." },
  { month: 7, day: 4, name: "Anni-Frid Lyngstad", profession: "Singer", region: "Global", star: "ABBA's golden-voiced princess whose Dancing Queen harmonies filled the world." },
  { month: 7, day: 5, name: "Wilma Rudolph", profession: "Sprinter", region: "Sports", star: "The first American woman to win three gold medals in a single Olympics against all odds." },
  { month: 7, day: 5, name: "Jürgen Klopp", profession: "Football manager", region: "Sports", star: "The charismatic German whose gegenpressing philosophy transformed Liverpool FC." },
  { month: 7, day: 6, name: "Dalai Lama", profession: "Spiritual leader", region: "Global", star: "The living symbol of Tibetan peace whose smile and wisdom transcend all borders." },
  { month: 7, day: 6, name: "Sandra Oh", profession: "Actor", region: "Hollywood", star: "A groundbreaking Korean-Canadian actress who redefined Asian representation on television." },
  { month: 7, day: 7, name: "Marc Chagall", profession: "Painter", region: "Global", star: "The dreamlike painter whose floating lovers and flying violins are pure visual poetry." },
  { month: 7, day: 8, name: "Billy Crudup", profession: "Actor", region: "Hollywood", star: "A Tony-winning stage and screen actor whose subtle intensity elevates every project." },
  { month: 7, day: 9, name: "Kesha", profession: "Singer", region: "Global", star: "The pop survivor whose fight for artistic freedom turned into an anthem of resilience." },
  { month: 7, day: 9, name: "Ollie Johnston", profession: "Animator", region: "Hollywood", star: "One of Disney's Nine Old Men whose hand-drawn characters still define animation." },
  { month: 7, day: 10, name: "Nikola Tesla", profession: "Inventor", region: "Global", star: "The genius who lit the world with alternating current and dreamed of wireless energy." },
  { month: 7, day: 10, name: "Jessica Simpson", profession: "Singer & entrepreneur", region: "Global", star: "The pop princess turned billion-dollar fashion mogul who proved reinvention is queen." },
  { month: 7, day: 11, name: "Yul Brynner", profession: "Actor", region: "Hollywood", star: "The bald, magnetic King and I star whose commanding presence defined exotic Hollywood." },
  { month: 7, day: 11, name: "Richie Sambora", profession: "Musician", region: "Global", star: "Bon Jovi's guitar hero whose riffs powered some of rock's biggest anthems." },
  { month: 7, day: 12, name: "Bill Cosby", profession: "Comedian & actor", region: "Hollywood", star: "A comedian whose legacy became deeply complicated by personal actions." },
  { month: 7, day: 12, name: "Christine McVie", profession: "Singer", region: "Global", star: "Fleetwood Mac's heart and soul whose Songbird and Everywhere still comfort millions." },
  { month: 7, day: 14, name: "Gerald Ford", profession: "President", region: "Global", star: "The only president never elected to the office who healed a wounded nation." },
  { month: 7, day: 14, name: "Conan O'Brien", profession: "Comedian & TV host", region: "Hollywood", star: "The gangly redhead whose self-deprecating wit made late-night comedy an art form." },
  { month: 7, day: 15, name: "Jacqueline Kennedy Onassis", profession: "First Lady", region: "Global", star: "The most glamorous First Lady whose elegance and courage defined Camelot." },
  { month: 7, day: 15, name: "Arianna Grande", profession: "Singer", region: "Global", star: "The pop powerhouse whose whistle notes and dramatic flair dominate every chart." },
  { month: 7, day: 16, name: "Stuart Sutcliffe", profession: "Artist & musician", region: "Global", star: "The forgotten Beatle whose artistic eye helped shape the band's visual identity." },
  { month: 7, day: 16, name: "Will Ferrell", profession: "Comedian & actor", region: "Hollywood", star: "The most committed silly man in comedy whose commitment makes the absurd hilarious." },
  { month: 7, day: 17, name: "Mike Tyson", profession: "Boxer", region: "Sports", star: "The youngest heavyweight champion whose ferocity in the ring was matched only by his complexity." },
  { month: 7, day: 17, name: "David Hasselhoff", profession: "Actor & singer", region: "Hollywood", star: "The Hoff, whose Knight Rider and Baywatch fame made him a global pop culture icon." },
  { month: 7, day: 18, name: "Elizabeth Gilbert", profession: "Author", region: "Global", star: "The Eat Pray Love author whose personal journey became a worldwide inspiration." },
  { month: 7, day: 19, name: "Lindsay Wagner", profession: "Actor", region: "Hollywood", star: "The Bionic Woman whose Emmy-winning role pioneered female action heroes on television." },
  { month: 7, day: 20, name: "Carlos Santana", profession: "Guitarist", region: "Global", star: "The guitarist who married Latin fire to rock and roll at Woodstock and beyond." },
  { month: 7, day: 20, name: "Aisha Tyler", profession: "Comedian & actor", region: "Hollywood", star: "A multihyphenate whose intelligence and humor make her a Renaissance woman of comedy." },
  { month: 7, day: 21, name: "Robin Williams", profession: "Comedian & actor", region: "Hollywood", star: "The boundless comic genius whose manic energy and tender roles touched every heart." },
  { month: 7, day: 22, name: "Selena Gomez", profession: "Singer & actor", region: "Hollywood", star: "A Disney alum turned pop star and mental health advocate whose honesty inspires millions." },
  { month: 7, day: 24, name: "Amelia Earhart", profession: "Aviator", region: "Global", star: "The pioneering pilot whose mysterious disappearance only deepened her legend." },
  { month: 7, day: 24, name: "George Bernard Shaw", profession: "Playwright", region: "Global", star: "The Irish wit whose Pygmalion and Man of Superman challenged every convention." },
  { month: 7, day: 27, name: "Bret Hart", profession: "Wrestler", region: "Sports", star: "The Excellence of Execution whose technical mastery made him the wrestler's wrestler." },
  { month: 7, day: 27, name: "Keke Palmer", profession: "Actor & singer", region: "Hollywood", star: "A child prodigy turned multi-hyphenate who owns every room she enters with fearless energy." },
  { month: 7, day: 29, name: "Mickey Rooney", profession: "Actor", region: "Hollywood", star: "A child star who worked for nearly nine decades in Hollywood with tireless energy." },
  { month: 7, day: 29, name: "Sofia Coppola", profession: "Director", region: "Hollywood", star: "The dreamy auteur whose Lost in Translation captured the beauty of loneliness." },
  { month: 7, day: 30, name: "Henry Ford", profession: "Industrialist", region: "Global", star: "The assembly line visionary who put the world on wheels and revolutionized manufacturing." },
  { month: 7, day: 30, name: "Lisa Kudrow", profession: "Actor", region: "Hollywood", star: "The lovable Phoebe whose quirky comedy and producing talent span far beyond Central Perk." },

  // ===== AUGUST =====
  { month: 8, day: 1, name: "Louis Armstrong", profession: "Trumpeter & singer", region: "Global", star: "Satchmo, the jazz ambassador whose grin and gravel voice made the world sing along." },
  { month: 8, day: 2, name: "James Cameron", profession: "Director", region: "Hollywood", star: "The deep-sea visionary behind Titanic and Avatar who keeps pushing cinema's boundaries." },
  { month: 8, day: 2, name: "Mary-Louise Parker", profession: "Actor", region: "Hollywood", star: "A Tony and Emmy winner whose understated performances carry tremendous emotional weight." },
  { month: 8, day: 3, name: "Martha Stewart", profession: "Entrepreneur", region: "Global", star: "The domestic goddess who built an empire from a single catering business." },
  { month: 8, day: 4, name: "Louis Armstrong", profession: "Musician", region: "Global", star: "The jazz pioneer whose gravelly voice and trumpet changed the course of American music." },
  { month: 8, day: 4, name: "Billy Bob Thornton", profession: "Actor & writer", region: "Hollywood", star: "An Oscar-winning Texan whose unpredictable intensity keeps audiences riveted." },
  { month: 8, day: 6, name: "Alfred Hitchcock", profession: "Director", region: "Hollywood", star: "The Master of Suspense whose silhouette and innovations still define cinematic fear." },
  { month: 8, day: 6, name: "Robert De Niro", profession: "Actor", region: "Hollywood", star: "The method king whose Taxi Driver and Goodfellas performances remain the gold standard." },
  { month: 8, day: 8, name: "Dustin Hoffman", profession: "Actor", region: "Hollywood", star: "A chameleon whose Rain Man and Kramer vs. Kramer showed the power of quiet intensity." },
  { month: 8, day: 9, name: "Whitney Houston", profession: "Singer", region: "Global", star: "The Voice whose I Will Always Love You became the most powerful pop ballad ever recorded." },
  { month: 8, day: 11, name: "Hulk Hogan", profession: "Wrestler", region: "Sports", star: "The most recognized face in wrestling history, brother, whose charisma transcended the ring." },
  { month: 8, day: 11, name: "Viola Davis", profession: "Actor", region: "Hollywood", star: "An EGOT winner whose raw power and vulnerability redefine what acting can achieve." },
  { month: 8, day: 12, name: "Pete Sampras", profession: "Tennis player", region: "Sports", star: "The gentleman champion whose 14 Grand Slam titles set the standard for tennis excellence." },
  { month: 8, day: 12, name: "Cara Delevingne", profession: "Model & actor", region: "Hollywood", star: "The bold British model-actress whose brows and bravado made her a fashion force." },
  { month: 8, day: 13, name: "Fidel Castro", profession: "Statesman", region: "Global", star: "The revolutionary leader whose 50-year rule made Cuba a Cold War flashpoint." },
  { month: 8, day: 13, name: "Sebastian Stan", profession: "Actor", region: "Hollywood", star: "The Winter Soldier whose brooding intensity brought depth to the Marvel Universe." },
  { month: 8, day: 14, name: "Eartha Kitt", profession: "Singer & actor", region: "Global", star: "The sultry voice behind Santa Baby who lived fearlessly across continents and careers." },
  { month: 8, day: 14, name: "Halle Berry", profession: "Actor", region: "Hollywood", star: "The first Black woman to win Best Actress, whose grace and grit opened doors forever." },
  { month: 8, day: 15, name: "Napoleon Bonaparte", profession: "Military leader", region: "Global", star: "The Corsican conqueror whose empire stretched from Spain to Russia in a flash of genius." },
  { month: 8, day: 15, name: "Jennifer Lawrence", profession: "Actor", region: "Hollywood", star: "The Oscar winner whose down-to-earth charm made Hollywood's biggest franchise feel human." },
  { month: 8, day: 16, name: "Annie Oakley", profession: "Sharpshooter", region: "Global", star: "The legendary markswoman who proved that a woman could outgun any man on the frontier." },
  { month: 8, day: 17, name: "Robert De Niro Sr.", profession: "Painter", region: "Global", star: "An abstract expressionist painter whose work influenced a generation of American art." },
  { month: 8, day: 17, name: "Davy Crockett", profession: "Frontiersman", region: "Global", star: "The King of the Wild Frontier whose legend grew taller with every telling." },
  { month: 8, day: 18, name: "Merle Haggard", profession: "Singer", region: "Global", star: "The country outlaw whose honky-tonk anthems defined working-class America." },
  { month: 8, day: 19, name: "Bill Clinton", profession: "President", region: "Global", star: "The charismatic 42nd president whose policy and personal drama shaped the 1990s." },
  { month: 8, day: 19, name: "Matthew Perry", profession: "Actor", region: "Hollywood", star: "The beloved Chandler Bing whose humor and candor about addiction moved the world." },
  { month: 8, day: 20, name: "Jacqueline Bisset", profession: "Actor", region: "Hollywood", star: "A British beauty whose sophisticated elegance defined international cinema in the 1960s." },
  { month: 8, day: 21, name: "Josephine Baker", profession: "Dancer & activist", region: "Global", star: "The Banana Skirt dancer who became a French Resistance spy and civil rights hero." },
  { month: 8, day: 21, name: "Wilt Chamberlain", profession: "Basketball player", region: "Sports", star: "The 100-point man whose athletic dominance still defies belief." },
  { month: 8, day: 22, name: "Hannah Arendt", profession: "Philosopher", region: "Global", star: "The thinker whose concept of the banality of evil changed how we understand atrocity." },
  { month: 8, day: 23, name: "Barbara Jordan", profession: "Politician", region: "Global", star: "The Texas congresswoman whose powerful voice during Watergate reminded America of its ideals." },
  { month: 8, day: 24, name: "Stephen Fry", profession: "Actor & writer", region: "Global", star: "A British polymath whose wit, intellect and openness make him a national treasure." },
  { month: 8, day: 25, name: "Sean Connery", profession: "Actor", region: "Hollywood", star: "The original James Bond whose Scottish brogue and machismo defined a franchise." },
  { month: 8, day: 25, name: "Tim Burton", profession: "Director", region: "Hollywood", star: "The gothic visionary whose dark fairy tales brought imagination to the mainstream." },
  { month: 8, day: 26, name: "Kenny Rogers", profession: "Singer", region: "Global", star: "The Gambler whose storytelling songs made country music a universal language." },
  { month: 8, day: 26, name: "Macaulay Culkin", profession: "Actor", region: "Hollywood", star: "The original Home Alone kid whose booby traps made him the most famous child on Earth." },
  { month: 8, day: 27, name: "Mother Teresa", profession: "Humanitarian", region: "Global", star: "The nun who dedicated her life to serving the poorest of the poor in Calcutta." },
  { month: 8, day: 28, name: "Jack Black", profession: "Actor & musician", region: "Hollywood", star: "The Tenacious D frontman whose manic energy and musical comedy are uniquely his own." },
  { month: 8, day: 28, name: "Vishwanathan Anand", profession: "Chess champion", region: "Global", star: "The Indian chess legend who became the first Asian to win the World Chess Championship." },
  { month: 8, day: 29, name: "John McCain", profession: "Senator", region: "Global", star: "The Arizona senator and POW whose honor and maverick spirit defined political courage." },
  { month: 8, day: 29, name: "Lea Michele", profession: "Actor & singer", region: "Hollywood", star: "The Glee star whose Broadway voice and emotional performances defined a musical era." },
  { month: 8, day: 30, name: "Cameron Diaz", profession: "Actor", region: "Hollywood", star: "The sunny California girl whose infectious laugh made her the rom-com queen of the 2000s." },
  { month: 8, day: 31, name: "Alan Rickman", profession: "Actor", region: "Global", star: "The velvet-voiced Snape whose villainous charm and wit made him beloved worldwide." },
  { month: 8, day: 31, name: "Chris Pine", profession: "Actor", region: "Hollywood", star: "The blue-eyed star who brought charisma to Captain Kirk and the Wonder Woman world." },

  // ===== SEPTEMBER =====
  { month: 9, day: 1, name: "Ann Bancroft", profession: "Explorer", region: "Global", star: "The first woman to reach both the North and South Poles, a trailblazer in every sense." },
  { month: 9, day: 2, name: "Paul Walker", profession: "Actor", region: "Hollywood", star: "The Fast and Furious star whose warmth and humanitarian spirit live on in memory." },
  { month: 9, day: 2, name: "Mark-Paul Gosselaar", profession: "Actor", region: "Hollywood", star: "Zack Morris to Detective Sassone, a '90s icon who grew up on screen with charm." },
  { month: 9, day: 4, name: "Fridtjof Nansen", profession: "Explorer & diplomat", region: "Global", star: "The Norwegian polymath who reached the Arctic and won the Nobel Peace Prize." },
  { month: 9, day: 5, name: "Raquel Welch", profession: "Actor", region: "Hollywood", star: "The bikini-clad icon of One Million Years B.C. who broke the mold of Hollywood beauty." },
  { month: 9, day: 6, name: "Idris Elba", profession: "Actor & DJ", region: "Hollywood", star: "The Stringer Bell turned Luther turned Heimdall, a British powerhouse of screen and sound." },
  { month: 9, day: 7, name: "Buddy Holly", profession: "Singer", region: "Global", star: "The bespectacled pioneer of rock and roll whose brief flame changed music forever." },
  { month: 9, day: 7, name: "Ann-Margret", profession: "Actor & singer", region: "Hollywood", star: "The Swedish-American firecracker whose Vegas showmanship matched her film stardom." },
  { month: 9, day: 8, name: "Pope John Paul II", profession: "Religious leader", region: "Global", star: "The Polish pope whose globe-trotting diplomacy helped end the Cold War." },
  { month: 9, day: 8, name: "Ke Huy Quan", profession: "Actor", region: "Hollywood", star: "The Everything Everywhere star whose Oscar comeback story is pure Hollywood magic." },
  { month: 9, day: 9, name: "Adam Sandler", profession: "Actor & comedian", region: "Hollywood", star: "The Happy Gilmore king whose goofy heart and Netflix empire make him unstoppable." },
  { month: 9, day: 10, name: "Arnold Palmer", profession: "Golfer", region: "Sports", star: "The King of golf whose charisma and skill made the sport mainstream." },
  { month: 9, day: 10, name: "Colin Firth", profession: "Actor", region: "Hollywood", star: "The Darcy of our dreams whose King's Speech Oscar cemented his place in cinema history." },
  { month: 9, day: 11, name: "Henry VIII", profession: "Monarch", region: "Global", star: "The Tudor king whose six wives and break with Rome changed England and Christianity forever." },
  { month: 9, day: 11, name: "Laura Ingram", profession: "TV host", region: "Hollywood", star: "The conservative commentator whose sharp rhetoric shapes nightly political conversation." },
  { month: 9, day: 12, name: "Jesse Owens", profession: "Sprinter", region: "Sports", star: "The Olympic hero who shattered Hitler's Aryan supremacy myth in Berlin in 1936." },
  { month: 9, day: 12, name: "Jennifer Hudson", profession: "Singer & actor", region: "Hollywood", star: "An EGOT winner whose voice soared from American Idol to Dreamgirls to Broadway." },
  { month: 9, day: 13, name: "Roald Dahl", profession: "Author", region: "Global", star: "The Welsh storyteller whose Charlie and the Chocolate Factory and Matilda enchanted children worldwide." },
  { month: 9, day: 13, name: "Nell Carter", profession: "Actor & singer", region: "Hollywood", star: "The vivacious Gimme a Break star whose powerful voice and humor lit up every room." },
  { month: 9, day: 14, name: "Amy Winehouse", profession: "Singer", region: "Global", star: "The jazz-soul siren whose Back to Black voice burned too bright and too brief." },
  { month: 9, day: 15, name: "Agatha Christie", profession: "Author", region: "Global", star: "The Queen of Crime whose plots kept the world guessing and her records remain unbroken." },
  { month: 9, day: 15, name: "Lisa Vanderpump", profession: "TV personality", region: "Hollywood", star: "The Vanderpump Rules queen whose diamonds and rosé dominate reality television." },
  { month: 9, day: 17, name: "Basil Rathbone", profession: "Actor", region: "Hollywood", star: "The definitive Sherlock Holmes of cinema, whose swashbuckling swordplay was equally legendary." },
  { month: 9, day: 17, name: "Doug E. Fresh", profession: "Rapper", region: "Global", star: "The Human Beatbox whose vocal percussion revolutionized hip-hop's sonic possibilities." },
  { month: 9, day: 18, name: "Lance Armstrong", profession: "Cyclist", region: "Sports", star: "The cyclist whose Tour de France titles and subsequent fall became sports' greatest cautionary tale." },
  { month: 9, day: 19, name: "Jeremy Irons", profession: "Actor", region: "Global", star: "An Oscar winner whose silky voice and moral complexity make every villain unforgettable." },
  { month: 9, day: 20, name: "Sophia Loren", profession: "Actor", region: "Hollywood", star: "The timeless Italian goddess whose beauty and talent conquered Hollywood and the world." },
  { month: 9, day: 20, name: "George R. R. Martin", profession: "Author", region: "Global", star: "The Game of Thrones creator who killed more beloved characters than anyone in fiction." },
  { month: 9, day: 22, name: "Billie Jean King", profession: "Tennis player", region: "Sports", star: "The activist champion whose Battle of the Sexes match changed women's sports forever." },
  { month: 9, day: 22, name: "Tom Felton", profession: "Actor", region: "Hollywood", star: "Draco Malfoy himself, whose charm off-screen won over the fans his character alienated." },
  { month: 9, day: 23, name: "August Macke", profession: "Painter", region: "Global", star: "A German Expressionist whose vibrant colors were cut short by the tragedy of World War I." },
  { month: 9, day: 23, name: "Bruce Springsteen", profession: "Singer", region: "Global", star: "The Boss whose anthems of working-class struggle turned New Jersey into rock mythology." },
  { month: 9, day: 24, name: "F. Scott Fitzgerald", profession: "Author", region: "Global", star: "The Jazz Age chronicler whose Great Gatsby defined the American Dream's shimmer and decay." },
  { month: 9, day: 25, name: "Michael Douglas", profession: "Actor & producer", region: "Hollywood", star: "An Oscar-winning dynasty heir whose Wall Street shark and romantic leads span decades." },
  { month: 9, day: 25, name: "Mark Hamill", profession: "Actor", region: "Hollywood", star: "Luke Skywalker and the voice of the Joker, a beloved icon of fantasy and animation." },
  { month: 9, day: 26, name: "George Gershwin", profession: "Composer", region: "Global", star: "The Rhapsody in Blue genius who married jazz and classical into American music." },
  { month: 9, day: 26, name: "Olivia Newton-John", profession: "Singer & actor", region: "Global", star: "Sandy from Grease whose I Honestly Love You and cancer advocacy inspired millions." },
  { month: 9, day: 27, name: "Micheal Graves", profession: "Architect", region: "Global", star: "The postmodern architect whose playful designs brought color back to buildings." },
  { month: 9, day: 27, name: "Gwyneth Paltrow", profession: "Actor & entrepreneur", region: "Hollywood", star: "An Oscar winner turned Goop mogul whose lifestyle brand polarizes and fascinates." },
  { month: 9, day: 29, name: "Kevin Hart", profession: "Comedian & actor", region: "Hollywood", star: "The pocket rocket of comedy whose relentless hustle made him a box-office giant." },
  { month: 9, day: 29, name: "Tàpies", profession: "Painter", region: "Global", star: "The Catalan abstract master whose textured works bridged art and philosophy." },

  // ===== OCTOBER =====
  { month: 10, day: 1, name: "Jimmy Carter", profession: "President", region: "Global", star: "The peanut farmer turned president whose post-office humanitarian work eclipsed his presidency." },
  { month: 10, day: 1, name: "Brie Larson", profession: "Actor", region: "Hollywood", star: "Captain Marvel and Room's Oscar winner whose strength and advocacy redefine modern stardom." },
  { month: 10, day: 2, name: "Kelly Ripa", profession: "TV host", region: "Hollywood", star: "The morning show queen whose quick wit and chemistry make every morning brighter." },
  { month: 10, day: 3, name: "Gore Vidal", profession: "Author", region: "Global", star: "The acerbic American intellectual whose essays and novels skewered power with elegant precision." },
  { month: 10, day: 3, name: "Chloe Sevigny", profession: "Actor & model", region: "Hollywood", star: "The indie darling and fashion icon whose quirky style and acting defy categorization." },
  { month: 10, day: 4, name: "Buster Keaton", profession: "Comedian & filmmaker", region: "Hollywood", star: "The Great Stone Face whose physical comedy genius rivaled Chaplin's." },
  { month: 10, day: 4, name: "Alicia Vikander", profession: "Actor", region: "Hollywood", star: "A Swedish Oscar winner whose quiet intensity and versatility light up every frame." },
  { month: 10, day: 5, name: "Taron Egerton", profession: "Actor", region: "Hollywood", star: "The Kingsman and Rocketman star whose charisma leaps off the screen." },
  { month: 10, day: 6, name: "LeBron James", profession: "Basketball player", region: "Sports", star: "The King whose two-decade reign made him the greatest all-around basketball player alive." },
  { month: 10, day: 6, name: "Elisabeth Shue", profession: "Actor", region: "Hollywood", star: "The Karate Kid and Leaving Las Vegas star whose relatable warmth defines screen charm." },
  { month: 10, day: 7, name: "Desmond Tutu", profession: "Archbishop", region: "Global", star: "The laughing archbishop whose anti-apartheid moral clarity earned a Nobel Peace Prize." },
  { month: 10, day: 7, name: "Toni Braxton", profession: "Singer", region: "Global", star: "The sultry R&B queen whose Un-Break My Heart became an anthem of heartbreak." },
  { month: 10, day: 9, name: "John Lennon", profession: "Singer", region: "Global", star: "The Beatle whose Imagine remains humanity's most hopeful song." },
  { month: 10, day: 9, name: "Guillermo del Toro", profession: "Director", region: "Global", star: "The Mexican auteur whose gothic fantasies and Oscar-winning Shape of Water span monsters and magic." },
  { month: 10, day: 10, name: "Boris Johnson", profession: "Prime Minister", region: "Global", star: "The blonde, bumbling British PM whose Brexit era was as chaotic as his hair." },
  { month: 10, day: 10, name: "Mario Lopez", profession: "TV host & actor", region: "Hollywood", star: "The Saved by the Bell heartthrob who became a beloved entertainment host." },
  { month: 10, day: 11, name: "Eleanor Roosevelt", profession: "First Lady", region: "Global", star: "The most activist First Lady in history, whose Human Rights Declaration still guides the world." },
  { month: 10, day: 11, name: "Art Garfunkel", profession: "Singer", region: "Global", star: "The golden voice half of Simon & whose Bridge Over Troubled Water still heals." },
  { month: 10, day: 13, name: "Paul Simon", profession: "Singer & songwriter", region: "Global", star: "The poetic half of Simon & Garfunkel whose solo career wove world music into folk." },
  { month: 10, day: 12, name: "Hugh Jackman", profession: "Actor", region: "Hollywood", star: "The Wolverine and Broadway star whose talent and humility make him Hollywood's nicest guy." },
  { month: 10, day: 14, name: "Dwight D. Eisenhower", profession: "General & president", region: "Global", star: "The Supreme Commander who led D-Day and then led the nation in peace." },
  { month: 10, day: 14, name: "Usher", profession: "Singer", region: "Global", star: "An R&B icon whose smooth moves and falsetto define modern soul." },
  { month: 10, day: 15, name: "Virgil", profession: "Poet", region: "Global", star: "The Roman poet whose Aeneid became the foundational epic of Western civilization." },
  { month: 10, day: 15, name: "Sarah Jessica Parker", profession: "Actor", region: "Hollywood", star: "Carrie Bradshaw herself, the fashion icon who made Manolo Blahnik a household name." },
  { month: 10, day: 16, name: "Noah Baumbach", profession: "Director & writer", region: "Hollywood", star: "The indie auteur whose Marriage Story and Frances Ha capture modern relationships with raw precision." },
  { month: 10, day: 16, name: "Tie-dye Day", profession: "Cultural moment", region: "Global", star: "A day to celebrate the groovy patterns that defined an era of peace and love." },
  { month: 10, day: 17, name: "Mila Kunis", profession: "Actor", region: "Hollywood", star: "From That '70s Show to Black Swan, a Ukrainian-born star who conquered Hollywood with wit." },
  { month: 10, day: 17, name: "Vivek Bindra", profession: "Entrepreneur", region: "Global", star: "The Indian business coach whose motivational empire inspires millions of entrepreneurs." },
  { month: 10, day: 18, name: "Zelda Rubinstein", profession: "Actor", region: "Hollywood", star: "The Poltergeist medium whose unforgettable 'They're here!' became horror's most quoted line." },
  { month: 10, day: 18, name: "Dave Grohl", profession: "Musician", region: "Global", star: "The Nirvana drummer turned Foo Fighters frontman, rock's most lovable workaholic." },
  { month: 10, day: 19, name: "Peter Max", profession: "Artist", region: "Global", star: "The pop art visionary whose psychedelic colors defined an era of cosmic creativity." },
  { month: 10, day: 19, name: "John Lithgow", profession: "Actor", region: "Hollywood", star: "The towering talent who can be terrifyingly alien or lovably goofy with equal skill." },
  { month: 10, day: 20, name: "Joaquin Phoenix", profession: "Actor", region: "Hollywood", star: "The Oscar-winning Joker whose intense, fearless performances leave audiences shaken." },
  { month: 10, day: 20, name: "Snoop Dogg", profession: "Rapper & TV personality", region: "Hollywood", star: "The Long Beach legend whose laid-back flow and cultural reinvention span three decades." },
  { month: 10, day: 21, name: "Benjamin Netanyahu", profession: "Prime Minister", region: "Global", star: "Israel's longest-serving PM whose political survival and controversial policies shape the Middle East." },
  { month: 10, day: 21, name: "Kim Kardashian", profession: "Media personality", region: "Hollywood", star: "The reality star turned billionaire businesswoman whose empire is built on cultural saturation." },
  { month: 10, day: 23, name: "Pelé", profession: "Footballer", region: "Sports", star: "The King of Football whose three World Cup titles made him the sport's first global superstar." },
  { month: 10, day: 23, name: "Weird Al Yankovic", profession: "Comedian & musician", region: "Hollywood", star: "The parody king whose accordion-fueled humor has spanned four decades of pop culture." },
  { month: 10, day: 24, name: "Monica Lewinsky", profession: "Public figure", region: "Global", star: "The woman at the center of a political scandal who reclaimed her narrative with grace." },
  { month: 10, day: 26, name: "Mahatma Gandhi", profession: "Political leader", region: "Global", star: "The father of India's independence whose nonviolent resistance changed the world forever." },
  { month: 10, day: 26, name: "Pat Sajak", profession: "TV host", region: "Hollywood", star: "The Wheel of Fortune host whose charming banter made him a living room fixture." },
  { month: 10, day: 27, name: "Sylvester Stallone", profession: "Actor & writer", region: "Hollywood", star: "Rocky and Rambo, the underdog whose written-in-blood determination inspired a generation." },
  { month: 10, day: 28, name: "Bill Gates", profession: "Entrepreneur", region: "Global", star: "The tech titan who put a computer on every desk and then set out to save the world." },
  { month: 10, day: 29, name: "Ben Vereen", profession: "Actor & dancer", region: "Hollywood", star: "The Tony-winning performer whose Ziggy energy on Broadway lit up an era." },
  { month: 10, day: 29, name: "Winona Ryder", profession: "Actor", region: "Hollywood", star: "The '90s indie queen who made a supernatural comeback as Stranger Things' beloved mom." },
  { month: 10, day: 30, name: "Grace Slick", profession: "Singer", region: "Global", star: "Jefferson Airplane's psychedelic queen whose White Rabbit trip never ended." },
  { month: 10, day: 31, name: "Vanilla Ice", profession: "Rapper", region: "Global", star: "The rapper whose Ice Ice Baby became the first hip-hop single to top the Billboard charts." },
  { month: 10, day: 31, name: "Kate Jackson", profession: "Actor", region: "Hollywood", star: "The smart Angel of Charlie's Angels whose directing ambitions pushed television boundaries." },

  // ===== NOVEMBER =====
  { month: 11, day: 1, name: "Toni Morrison", profession: "Author", region: "Global", star: "The Nobel laureate whose Beloved gave voice to the unspeakable truths of slavery." },
  { month: 11, day: 1, name: "Lyle Lovett", profession: "Singer", region: "Global", star: "The Texan troubadour whose quirky country-pop and towering hair are equally iconic." },
  { month: 11, day: 2, name: "Kamala Harris", profession: "Vice President", region: "Global", star: "The first female, Black, and South Asian Vice President who broke the ultimate glass ceiling." },
  { month: 11, day: 2, name: "David Schwimmer", profession: "Actor", region: "Hollywood", star: "Ross Geller himself, whose physical comedy and advocacy work span far beyond Central Perk." },
  { month: 11, day: 3, name: "Diana Ross", profession: "Singer", region: "Global", star: "The Supremes diva whose glamour and voice made her the Empress of Soul." },
  { month: 11, day: 3, name: "Lamar Odom", profession: "Basketball player", region: "Sports", star: "The NBA champion whose on-court brilliance and personal struggles played out in public." },
  { month: 11, day: 4, name: "Will Smith", profession: "Actor & rapper", region: "Hollywood", star: "The Fresh Prince turned blockbuster king whose charisma spans music, TV and cinema." },
  { month: 11, day: 5, name: "Tilda Swinton", profession: "Actor", region: "Global", star: "The androgynous chameleon who disappears into every role with aristocratic otherworldliness." },
  { month: 11, day: 5, name: "Bryan Adams", profession: "Singer", region: "Global", star: "The Canadian rocker whose Summer of '69 and ballads filled arenas for decades." },
  { month: 11, day: 6, name: "Sally Field", profession: "Actor", region: "Hollywood", star: "The Oscar-winning actress whose you-like-me declaration became a feminist rallying cry." },
  { month: 11, day: 6, name: "Lorde", profession: "Singer", region: "Global", star: "The New Zealand prodigy whose Royals made her the voice of minimalist pop at just sixteen." },
  { month: 11, day: 8, name: "Bee Gees", profession: "Singers", region: "Global", star: "The Brothers Gibb whose falsetto harmonies defined disco and survived every era." },
  { month: 11, day: 8, name: "Sza", profession: "Singer", region: "Global", star: "The R&B auteur whose Control and SOS albums turned vulnerability into a chart-topping art form." },
  { month: 11, day: 10, name: "Jenna Elfman", profession: "Actor", region: "Hollywood", star: "The Dancing Fitness star whose comedic warmth made Dharma & Greg a beloved sitcom." },
  { month: 11, day: 12, name: "Ryan Gosling", profession: "Actor", region: "Hollywood", star: "The Notebook heartthrob turned La La Land leading man whose quiet cool defines modern cinema." },
  { month: 11, day: 12, name: "Grace Kelly", profession: "Actor & princess", region: "Hollywood", star: "The Hitchcock blonde who became real-life royalty, a fairy tale of beauty and poise." },
  { month: 11, day: 13, name: "Whoopi Goldberg", profession: "Comedian & actor", region: "Hollywood", star: "An EGOT winner whose wit, warmth and gravity make her Hollywood's most beloved truth-teller." },
  { month: 11, day: 13, name: "Chris Noth", profession: "Actor", region: "Hollywood", star: "Mr. Big himself, whose suave portrayal became a pop culture archetype." },
  { month: 11, day: 14, name: "Claudette Colbert", profession: "Actor", region: "Hollywood", star: "The It Happened One Night star whose sophisticated charm defined 1930s Hollywood glamour." },
  { month: 11, day: 14, name: "Nikolai Tesla", profession: "Inventor", region: "Global", star: "The Serbian genius who dreamed of wireless energy and tamed alternating current." },
  { month: 11, day: 15, name: "Petula Clark", profession: "Singer & actor", region: "Global", star: "The British pop pioneer whose Downtown topped charts on both sides of the Atlantic." },
  { month: 11, day: 15, name: "Shailene Woodley", profession: "Actor", region: "Hollywood", star: "The Divergent star whose environmental activism matches her indie film sensitivity." },
  { month: 11, day: 16, name: "Lisa Bonet", profession: "Actor", region: "Hollywood", star: "The ethereal Cosby Show and Affinity star whose free spirit defines cool." },
  { month: 11, day: 16, name: "Mahmoud Ahmadinejad", profession: "President", region: "Global", star: "The controversial Iranian president whose rhetoric made him a global flashpoint." },
  { month: 11, day: 18, name: "Oscar Wilde", profession: "Author", region: "Global", star: "The wit whose Dorian Gray and social comedies proved that style can be substance." },
  { month: 11, day: 18, name: "Jodie Foster", profession: "Actor & director", region: "Hollywood", star: "The two-time Oscar winner whose intelligence and privacy made her Hollywood's most respected mind." },
  { month: 11, day: 19, name: "Meg Ryan", profession: "Actor", region: "Hollywood", star: "The queen of romantic comedies whose When Harry Met Sally moment defined a genre." },
  { month: 11, day: 20, name: "Donald Trump Jr.", profession: "Businessman", region: "Global", star: "The eldest Trump son whose business and political life follow the family playbook." },
  { month: 11, day: 20, name: "Joe Biden", profession: "President", region: "Global", star: "The 46th president whose decades-long career in public service reached its pinnacle in the White House." },
  { month: 11, day: 21, name: "Harold Ramis", profession: "Actor & writer", region: "Hollywood", star: "Egon Spengler and the mind behind Groundhog Day, whose comedy was secretly philosophical." },
  { month: 11, day: 21, name: "Goldie Hawn", profession: "Actor", region: "Hollywood", star: "The bubbly Oscar winner whose laugh is the most contagious sound in Hollywood." },
  { month: 11, day: 23, name: "Harpo Marx", profession: "Comedian", region: "Hollywood", star: "The silent Marx Brother whose harp and honking horn brought wordless joy to millions." },
  { month: 11, day: 23, name: "Miley Cyrus", profession: "Singer & actor", region: "Hollywood", star: "The Hannah Montana alum who wrecked ball her way into a fearless pop reinvention." },
  { month: 11, day: 24, name: "Robert Vaughn", profession: "Actor", region: "Hollywood", star: "The Man from U.N.C.L.E. star whose sophisticated spy defined Cold War television cool." },
  { month: 11, day: 24, name: "Dana Delany", profession: "Actor", region: "Hollywood", star: "The China Beach star whose beauty, intelligence and wit span decades of quality television." },
  { month: 11, day: 25, name: "John F. Kennedy Jr.", profession: "Publisher", region: "Global", star: "The prince of Camelot whose charm and tragic death kept a dynasty in the headlines." },
  { month: 11, day: 25, name: "Kathleen Turner", profession: "Actor", region: "Hollywood", star: "The husky-voiced queen of 1980s cinema whose Romancing the Stone and Prizzi's Honor sizzled." },
  { month: 11, day: 26, name: "Alexander Graham Bell", profession: "Inventor", region: "Global", star: "The inventor of the telephone who connected the world with a single brilliant idea." },
  { month: 11, day: 26, name: "Nat Turner", profession: "Rebel leader", region: "Global", star: "The enslaved preacher whose 1831 rebellion struck fear into the institution of slavery." },
  { month: 11, day: 27, name: "Jimi Hendrix", profession: "Guitarist", region: "Global", star: "The left-handed genius who turned the guitar into a weapon of psychedelic revolution." },
  { month: 11, day: 27, name: "Robin Roberts", profession: "TV host", region: "Hollywood", star: "The Good Morning America anchor whose courage through illness inspired a nation." },
  { month: 11, day: 28, name: "Gloria Steinem", profession: "Activist", region: "Global", star: "The feminist icon whose Ms. Magazine and activism reshaped the women's movement forever." },
  { month: 11, day: 28, name: "Jon Stewart", profession: "Comedian", region: "Hollywood", star: "The Daily Show host whose satirical journalism defined political comedy for a generation." },
  { month: 11, day: 29, name: "Chuck Mangione", profession: "Musician", region: "Global", star: "The flugelhorn player whose Feel So Good became smooth jazz's most recognizable melody." },
  { month: 11, day: 29, name: "Howie Mandel", profession: "Comedian & TV host", region: "Hollywood", star: "The Deal or No Deal host whose germaphobia and comedy make him uniquely entertaining." },
  { month: 11, day: 30, name: "Mark Twain", profession: "Author", region: "Global", star: "The humorist whose wit about Mississippi River life remains America's literary conscience." },
  { month: 11, day: 30, name: "Ben Stiller", profession: "Actor & director", region: "Hollywood", star: "The Zoolander and Night at the Museum star whose deadpan comedy built a comedy empire." },

  // ===== DECEMBER =====
  { month: 12, day: 1, name: "Woody Allen", profession: "Director & writer", region: "Hollywood", star: "The neurotic auteur whose Manhattan comedies redefined intellectual humor in cinema." },
  { month: 12, day: 1, name: "Bette Midler", profession: "Singer & actor", region: "Hollywood", star: "The Divine Miss M whose powerhouse voice and camp energy define entertainment excess." },
  { month: 12, day: 2, name: "Julie Harris", profession: "Actor", region: "Hollywood", star: "A five-time Tony winner whose stage and screen work spanned five decades of American drama." },
  { month: 12, day: 2, name: "Britney Spears", profession: "Singer", region: "Global", star: "The Princess of Pop whose talent, trials and freedom fight captivated the entire world." },
  { month: 12, day: 3, name: "Amanda Seyfried", profession: "Actor", region: "Hollywood", star: "The Mamma Mia star whose wide-eyed beauty and talent span musicals and dark dramas." },
  { month: 12, day: 3, name: "Fernando Alonso", profession: "Racing driver", region: "Sports", star: "The two-time F1 champion whose relentless drive made him a global motorsport legend." },
  { month: 12, day: 5, name: "Walt Disney", profession: "Animator & entrepreneur", region: "Hollywood", star: "The dreamer who built an empire from a mouse and proved that imagination is limitless." },
  { month: 12, day: 5, name: "Kitty Wells", profession: "Singer", region: "Global", star: "The first female country solo artist to top the charts, the Queen of Country Music." },
  { month: 12, day: 6, name: "Dave Brubeck", profession: "Jazz musician", region: "Global", star: "The Time Out genius whose Take Five became jazz's most recognizable tune." },
  { month: 12, day: 6, name: "Tom Hulce", profession: "Actor", region: "Hollywood", star: "The Mozart of Amadeus whose manic energy on screen left an indelible mark." },
  { month: 12, day: 7, name: "Noam Chomsky", profession: "Linguist & author", region: "Global", star: "The intellectual powerhouse whose critiques of power and language reshaped modern thought." },
  { month: 12, day: 7, name: "Larry Bird", profession: "Basketball player", region: "Sports", star: "The Hick from French Lick whose rivalry with Magic made the NBA must-watch television." },
  { month: 12, day: 8, name: "David Carradine", profession: "Actor", region: "Hollywood", star: "The Kung Fu star whose martial arts screen presence spanned five decades." },
  { month: 12, day: 8, name: "Sinead O'Connor", profession: "Singer", region: "Global", star: "The fierce Irish voice whose Nothing Compares 2 U and activism were unapologetically raw." },
  { month: 12, day: 9, name: "John Milton", profession: "Poet", region: "Global", star: "The Paradise Lost author whose Satan became literature's most complex villain." },
  { month: 12, day: 9, name: "Donny Osmond", profession: "Singer & actor", region: "Hollywood", star: "The teen idol whose Puppy Love and Vegas residency span generations of fandom." },
  { month: 12, day: 11, name: "Carlos Slim Helú", profession: "Entrepreneur", region: "Global", star: "The Mexican telecoms titan who became the world's richest man on business genius." },
  { month: 12, day: 11, name: "Terrence Howard", profession: "Actor", region: "Hollywood", star: "The Hustle & Flow star whose intense performances carry both menace and vulnerability." },
  { month: 12, day: 12, name: "Frank Sinatra", profession: "Singer & actor", region: "Hollywood", star: "The Chairman of the Board whose velvet voice and Rat Pack cool defined an era." },
  { month: 12, day: 12, name: "Dionne Warwick", profession: "Singer", region: "Global", star: "The pop soul queen who asked What's It All About and answered with six Grammys." },
  { month: 12, day: 13, name: "Taylor Swift", profession: "Singer", region: "Global", star: "The songwriting prodigy who turned diary entries into the biggest music empire of her generation." },
  { month: 12, day: 13, name: "Jamie Foxx", profession: "Actor & singer", region: "Hollywood", star: "An Oscar-winning chameleon whose Ray Charles transformation and comedy skills are unmatched." },
  { month: 12, day: 14, name: "Vanessa Hudgens", profession: "Actor & singer", region: "Hollywood", star: "The High School Musical star who grew up on screen and conquered Broadway and film." },
  { month: 12, day: 15, name: "Jane Austen", profession: "Author", region: "Global", star: "The queen of wit whose Pride and Prejudice remains the template for romantic fiction." },
  { month: 12, day: 15, name: "Adam Brody", profession: "Actor", region: "Hollywood", star: "Seth Cohen from The O.C. whose indie cool and rom-com charm never faded." },
  { month: 12, day: 17, name: "Beatrix Potter", profession: "Author & illustrator", region: "Global", star: "The creator of Peter Rabbit whose children's tales and conservation work endure." },
  { month: 12, day: 18, name: "Keith Richards", profession: "Musician", region: "Global", star: "The Rolling Stone whose guitar riffs are as immortal and indestructible as the man himself." },
  { month: 12, day: 19, name: "Cicciolina", profession: "Actor & politician", region: "Global", star: "The Italian pornstar-turned-politician who proved art and politics can shock simultaneously." },
  { month: 12, day: 20, name: "Jonah Hill", profession: "Actor", region: "Hollywood", star: "The Superbad star turned Oscar nominee whose transformation proved indie credibility can come from anywhere." },
  { month: 12, day: 20, name: "Samuel L. Jackson", profession: "Actor", region: "Hollywood", star: "The highest-grossing actor in history whose every line reading is an event." },
  { month: 12, day: 21, name: "Jane Fonda", profession: "Actor & activist", region: "Hollywood", star: "The two-time Oscar winner and workout queen who turned protest into a second career." },
  { month: 12, day: 21, name: "Kiefer Sutherland", profession: "Actor", region: "Hollywood", star: "Jack Bauer himself, whose 24-hour intensity redefined the television thriller." },
  { month: 12, day: 22, name: "Giuseppe Verdi", profession: "Composer", region: "Global", star: "The Italian opera master whose Aida and La Traviata still make audiences weep." },
  { month: 12, day: 22, name: "Ralph Fiennes", profession: "Actor", region: "Global", star: "Voldemort and the English Patient star whose Shakespearean intensity graces every role." },
  { month: 12, day: 23, name: "Prince John", profession: "Royal", region: "Global", star: "The British royal whose quiet life contrasted dramatically with his brother's fame." },
  { month: 12, day: 23, name: "Helena Bonham Carter", profession: "Actor", region: "Hollywood", star: "The eccentric British star who brings delicious mischief to everything from period dramas to fairy tales." },
  { month: 12, day: 24, name: "Mary Higgins Clark", profession: "Author", region: "Global", star: "The Queen of Suspense whose page-turners kept millions reading through sleepless nights." },
  { month: 12, day: 25, name: "Isaac Newton", profession: "Physicist", region: "Global", star: "The apple-dropping genius whose laws of motion and gravity explained the universe." },
  { month: 12, day: 25, name: "Robert Redford", profession: "Actor & director", region: "Hollywood", star: "The Sundance Kid whose acting and indie film advocacy transformed Hollywood's landscape." },
  { month: 12, day: 26, name: "Charles Babbage", profession: "Inventor", region: "Global", star: "The father of computing whose Difference Engine conceptualized the digital age a century early." },
  { month: 12, day: 26, name: "Kit Harington", profession: "Actor", region: "Hollywood", star: "Jon Snow himself, whose brooding heroism made him the face of fantasy television." },
  { month: 12, day: 27, name: "Louis Pasteur", profession: "Scientist", region: "Global", star: "The microbiologist whose pasteurization process and vaccines saved millions of lives." },
  { month: 12, day: 27, name: "Emilia Clarke", profession: "Actor", region: "Hollywood", star: "Daenerys Targaryen herself, the Khaleesi whose beauty and talent conquered Westeros and Hollywood." },
  { month: 12, day: 28, name: "Maggie Smith", profession: "Actor", region: "Global", star: "Professor McGonagall and the Dowager Countess, a national treasure whose wit is razor-sharp." },
  { month: 12, day: 29, name: "Ted Danson", profession: "Actor", region: "Hollywood", star: "The Cheers legend whose everyman charm spans sitcoms, dramas and environmental activism." },
  { month: 12, day: 29, name: "Mary Tyler Moore", profession: "Actor", region: "Hollywood", star: "The TV icon who proved a single woman could be the hero of her own story." },
  { month: 12, day: 30, name: "Tiger Woods", profession: "Golfer", region: "Sports", star: "The golfing prodigy whose dominance and personal drama made him the sport's most complex legend." },
  { month: 12, day: 30, name: "Skrillex", profession: "DJ & producer", region: "Global", star: "The EDM pioneer whose bass drops reshaped electronic music and won eight Grammys." },
  { month: 12, day: 31, name: "Benjamin Disraeli", profession: "Prime Minister", region: "Global", star: "The Victorian PM and novelist whose charm and wit made politics a literary art." },
  { month: 12, day: 31, name: "Donna Summer", profession: "Singer", region: "Global", star: "The Queen of Disco whose Love to Love You Baby ignited the dance music revolution." },

  // ===== K-POP / THAI / BOLIYWOOD DIVERSITY =====
  { month: 1, day: 3, name: "Jisoo", profession: "Singer", region: "K-Pop", star: "The elegant global ambassador of BLACKPINK whose beauty and poise enchant the world." },
  { month: 1, day: 12, name: "D.O.", profession: "Singer & actor", region: "K-Pop", star: "EXO's soulful vocalist and rising actor whose range spans pop and cinema." },
  { month: 1, day: 14, name: "Kai", profession: "Singer & dancer", region: "K-Pop", star: "EXO's main dancer whose gravity-defying moves set the standard for K-pop performance." },
  { month: 1, day: 20, name: "Aum Patchrapa", profession: "Actor", region: "Thai", star: "A Thai screen queen whose luminous presence defined a golden era of lakorn drama." },
  { month: 1, day: 28, name: "Araya A. Hargate", profession: "Actor & model", region: "Thai", star: "The glamorous Thai actress and ambassador whose elegance dominates the screen." },
  { month: 2, day: 11, name: "Rosé", profession: "Singer", region: "K-Pop", star: "BLACKPINK's honey-voiced songstress whose melodies glow like rose gold." },
  { month: 2, day: 14, name: "Madhubala", profession: "Actor", region: "Bollywood", star: "The Venus of Indian cinema whose tragic beauty defined Bollywood's golden age." },
  { month: 2, day: 18, name: "J-Hope", profession: "Singer & dancer", region: "K-Pop", star: "BTS's sunshine whose radiant energy and dance mastery light up every stage." },
  { month: 4, day: 18, name: "Weir Sukollawat", profession: "Actor", region: "Thai", star: "A Thai heartthrob whose rugged charm and acting range span television and film." },
  { month: 3, day: 9, name: "Taeyeon", profession: "Singer", region: "K-Pop", star: "The queen of K-pop vocals whose ethereal voice leads Girls' Generation and beyond." },
  { month: 3, day: 14, name: "Aamir Khan", profession: "Actor & director", region: "Bollywood", star: "Mr. Perfectionist of Bollywood, whose daring films challenge and uplift a nation." },
  { month: 3, day: 15, name: "Alia Bhatt", profession: "Actor", region: "Bollywood", star: "A Bollywood phenom whose fearless roles have made her the defining star of her generation." },
  { month: 3, day: 21, name: "Rani Mukerji", profession: "Actor", region: "Bollywood", star: "A powerhouse performer whose fierce intensity and grace rule Bollywood's heart." },
  { month: 3, day: 27, name: "Lisa", profession: "Singer & dancer", region: "K-Pop", star: "BLACKPINK's Thai-born maestro whose rap flow and dance moves ignite stadiums worldwide." },
  { month: 3, day: 29, name: "Irene", profession: "Singer", region: "K-Pop", star: "Red Velvet's elegant leader whose ethereal visuals and calm grace define the group." },
  { month: 4, day: 24, name: "Varun Dhawan", profession: "Actor", region: "Bollywood", star: "A Bollywood leading man whose boyish energy and dance moves light up the screen." },
  { month: 5, day: 6, name: "Baekhyun", profession: "Singer", region: "K-Pop", star: "EXO's golden vocalist whose silky high notes turn every song into a masterpiece." },
  { month: 5, day: 16, name: "IU", profession: "Singer & actor", region: "K-Pop", star: "Korea's beloved solo artist whose voice and acting touch millions of hearts." },
  { month: 5, day: 16, name: "Mai Davika", profession: "Actor & model", region: "Thai", star: "A Thai beauty icon whose striking presence and acting talent conquered Asia." },
  { month: 6, day: 26, name: "Arjun Kapoor", profession: "Actor", region: "Bollywood", star: "A versatile Bollywood actor navigating drama, action and romance with ease." },
  { month: 7, day: 6, name: "Ranveer Singh", profession: "Actor", region: "Bollywood", star: "A whirlwind of boundless energy whose electric performances define modern Bollywood." },
  { month: 7, day: 18, name: "Priyanka Chopra", profession: "Actor", region: "Bollywood", star: "India's global crossover superstar whose ambition made Bollywood shine in Hollywood." },
  { month: 9, day: 14, name: "Ayushmann Khurrana", profession: "Actor", region: "Bollywood", star: "The unlikely hero of Indian cinema whose bold stories dismantle social taboos." },
  { month: 9, day: 21, name: "Kareena Kapoor Khan", profession: "Actor", region: "Bollywood", star: "The begum of Bollywood whose effortless cool has reigned for two decades." },
  { month: 9, day: 22, name: "Nayeon", profession: "Singer", region: "K-Pop", star: "TWICE's radiant center whose bubblegum charm and steady vocals anchor the group." },
  { month: 9, day: 28, name: "Ranbir Kapoor", profession: "Actor", region: "Bollywood", star: "A dynasty heir who quietly became Bollywood's most celebrated method actor." },
  { month: 10, day: 11, name: "Amitabh Bachchan", profession: "Actor", region: "Bollywood", star: "The angry young man turned Indian cinema's most enduring megastar." },
  { month: 10, day: 27, name: "Aff Taksaorn", profession: "Actor", region: "Thai", star: "A Thai screen goddess whose classic dramas remain beloved across generations." },
  { month: 11, day: 9, name: "Momo", profession: "Singer & dancer", region: "K-Pop", star: "TWICE's Japanese-born dance machine whose moves electrify every stage." },
  { month: 12, day: 3, name: "Ken Theeradeth", profession: "Actor", region: "Thai", star: "A veteran Thai actor whose serious craft and screen presence define lakorn royalty." },
  { month: 12, day: 11, name: "Dilip Kumar", profession: "Actor", region: "Bollywood", star: "The Tragedy King of Bollywood whose method acting predated the method itself." },
  { month: 12, day: 12, name: "Rajinikanth", profession: "Actor", region: "Bollywood", star: "The superstar beyond superstars, whose legendary charm defies all explanation." },
  { month: 12, day: 14, name: "Raj Kapoor", profession: "Actor & director", region: "Bollywood", star: "The showman of Indian cinema whose tramp-inspired persona captured a nation's heart." },
  { month: 12, day: 17, name: "Nadech Kugimiya", profession: "Actor", region: "Thai", star: "Thailand's most beloved leading man whose award-winning craft spans film and TV." },
  { month: 12, day: 27, name: "Salman Khan", profession: "Actor", region: "Bollywood", star: "Bhai, the superstar whose larger-than-life presence commands India's box office." },
  { month: 12, day: 29, name: "Sana", profession: "Singer", region: "K-Pop", star: "TWICE's Japanese sweetheart whose sparkling energy and charm make her unforgettable." },
  { month: 12, day: 31, name: "PSY", profession: "Singer", region: "K-Pop", star: "The Gangnam Style phenomenon who turned K-pop into a global party." },
  { month: 1, day: 10, name: "Hrithik Roshan", profession: "Actor", region: "Bollywood", star: "The Greek god of Bollywood whose dance and action redefine every genre." },
  { month: 2, day: 27, name: "Zoheb Hassan", profession: "Singer", region: "Global", star: "The Pakistani pop pioneer whose duets with his sister defined South Asian pop." },
];
