import type { Theme } from "../astrology/interpret";

/**
 * Curated editorial fragments. Each fragment is a complete, human-written
 * sentence or clause that can be combined deterministically. The library is
 * deliberately large and varied to keep forecasts from repeating, while the
 * seeded random selection guarantees reproducibility.
 */

export interface Fragment {
  /** Only used when the fragment references a specific planet/transit. */
  planet?: string;
}

export const OVERVIEW_FRAGMENTS: readonly string[] = [
  "The quiet momentum of the day rewards steady, deliberate action over haste.",
  "A patient rhythm sets in, inviting you to move at your own measured pace.",
  "There is a stillness at the centre of the week that asks for reflection before action.",
  "Energy builds gradually, favouring those who begin small and build with care.",
  "The arc of the day bends toward clarity, one decision at a time.",
  "Notice how small choices compound into meaningful direction by evening.",
  "An undercurrent of possibility runs beneath the surface of the ordinary.",
  "The stars incline, but they do not compel; the choice remains yours.",
  "A sense of purpose sharpens as the hours unfold, giving weight to intention.",
  "Balance returns when you allow room for both concentration and ease.",
  "Familiar ground offers more opportunity than you first expect today.",
  "The horizon broadens when you release a rigid expectation you had been holding.",
  "Subtle shifts in perspective make the familiar feel newly promising.",
  "A recurring theme asks to be addressed with honesty rather than avoided.",
  "Your instincts are unusually reliable right now; give them room to speak.",
  "Progress comes through refinement rather than reinvention in this cycle.",
  "The day rewards preparation more than impulse, so ready your ground.",
  "A door that seemed closed begins to open by way of patience and follow-through.",
  "There's power in simplicity today; resist the urge to overcomplicate.",
  "Allow curiosity, not urgency, to be your guide through the hours ahead.",
  "The rhythm of the season supports going deep rather than going wide.",
  "A clearer sense of what matters emerges when you quiet the noise.",
  "What you water grows; tend to the commitments that truly matter.",
  "Expect a gentle recalibration of priorities as the day unfolds.",
  "The light you bring to small tasks today brightens the larger path.",
  "Movement feels more natural when it follows a considered direction.",
  "A forming plan takes shape more readily when you share it with a trusted voice.",
  "Reserve energy for what deserves you, and let the rest fall away.",
  "The middle of the period rewards consistency over intensity.",
  "Your capacity for focus is your quiet advantage right now.",
  "There is a particular clarity in the air that rewards decisive beginnings.",
  "A sense that something important is quietly aligning in your favour.",
  "The day asks for flexibility tempered by a steady hand on your intentions.",
  "A gentle turnaround in mood is more likely than any dramatic shift today.",
  "Patience with a process in motion will be rewarded before the period closes.",
  "The more you simplify your day, the more precise and powerful it becomes.",
  "A tension between obligation and desire resolves once you name it honestly.",
  "The wisdom of this cycle lies in waiting for the fuller picture to emerge.",
  "A recurring opportunity returns, this time with better timing on your side.",
  "You are better positioned than you realise to turn circumstance into advantage.",
  "The day's challenges are gentle, its rewards generous to those who persist.",
  "An old lesson returns in a new form, offering a second chance to apply it.",
  "The pace of life slows just enough for you to catch a meaningful detail.",
  "Circumstance favours the patient architect over the impatient builder.",
  "Small, sincere efforts accumulate into a foundation you can trust.",
  "There is a quiet dignity in doing unglamorous work well right now.",
  "The period rewards those who listen more than those who rush to speak.",
  "A change in rhythm invites you to work with a new, more sustainable tempo.",
  "Clarity arrives through action, not through further deliberation alone.",
  "The present moment holds more direction than any plan for the future.",
];

export const LOVE_INTRO: readonly string[] = [
  "In matters of the heart,",
  "When it comes to love,",
  "On the romantic front,",
  "For your closest connections,",
  "In partnership and affection,",
  "Around matters of the heart,",
  "In love and connection,",
  "Where intimacy is concerned,",
];

export const LOVE_BODY: readonly string[] = [
  "a warmer tone enters your words, making honesty feel easier than usual.",
  "listening becomes the greatest gift you can offer, and the rewards show quickly.",
  "a small gesture carries more weight than a grand one right now.",
  "vulnerability, offered gently, deepens the trust between you.",
  "the courage to say what you feel clears ground for greater closeness.",
  "old patterns loosen their hold, leaving room for a lighter rhythm.",
  "giving someone the benefit of the doubt strengthens the bond.",
  "shared humour lightens a moment that could otherwise weigh heavy.",
  "your presence becomes the reassurance someone close to you needs.",
  "asking for what you want, plainly, changes the dynamic for the better.",
  "a slower pace lets affection settle into something more lasting.",
  "reconnection with someone familiar may bring surprising warmth.",
  "appreciation, voiced out loud, lands more powerfully than silence.",
  "tenderness in your tone softens a conversation that had grown tense.",
  "showing up consistently matters more than any single grand display.",
  "a shared plan, however modest, draws you closer together.",
  "allowing joy to be simple takes the pressure off and lets love breathe.",
  "honouring your own needs makes room for genuine reciprocity.",
  "an honest question, asked kindly, opens a door you didn't expect.",
  "the comfort of being understood becomes the theme of the moment.",
  "an evening devoted to one another restores what busyness has thinned.",
  "offering reassurance without being asked reveals your devotion beautifully.",
  "a tender memory, revisited together, reconnects you to why you chose each other.",
  "letting go of a small grievance makes room for a larger affection.",
  "your willingness to be seen as you are is a gift you rarely recognise.",
  "sharing a hope you rarely voice draws someone closer to your inner world.",
  "a patient response where you might have reacted deepens mutual trust.",
  "giving space when it is needed proves you understand love's quiet side.",
  "affection expressed through everyday reliability outweighs any single moment.",
  "an unexpected act of consideration from someone close rewarms the bond.",
  "your honesty about a boundary reframes the relationship more healthily.",
  "choosing to be fully present is the truest declaration you can make.",
  "a kind word, offered at the right moment, carries you further than a grand gesture.",
  "the comfort of your company is felt more than you might imagine.",
  "revisiting a shared dream rekindles a sense of partnership and purpose.",
  "a gentle admission of need invites the closeness you have been wanting.",
  "patience with a loved one's timing honours the bond you share.",
  "your generosity of attention is the rarest and most valued currency.",
  "allowing your guard down, slowly, lets trust grow on firm ground.",
  "the pleasure of being known for who you are is the quiet theme of this time.",
];

export const CAREER_INTRO: readonly string[] = [
  "In your work,",
  "Professionally,",
  "On the career front,",
  "At work,",
  "In professional matters,",
  "Where your ambitions live,",
  "In your professional life,",
];

export const CAREER_BODY: readonly string[] = [
  "a clear priority emerges, and focusing on it yields visible gains.",
  "steady follow-through on an existing task carries more weight than a new idea.",
  "your reliability becomes your most persuasive argument.",
  "a conversation worth having is best approached with preparation, not reaction.",
  "the quality of your attention now is noticed by those who matter.",
  "collaboration brings out the best in a plan you have been shaping alone.",
  "asking a clarifying question protects you from a costly assumption.",
  "progress comes in measured steps; trust the process over the pace.",
  "a transition you have been anticipating begins to take clear shape.",
  "your contribution gains visibility when you speak with quiet confidence.",
  "organisation turns a crowded agenda into a manageable one.",
  "an opportunity to demonstrate initiative deserves your readiness.",
  "the right next move is the modest one that compounds over time.",
  "deadlines feel more manageable when broken into deliberate increments.",
  "mentorship, whether given or received, adds value to your direction.",
  "a meticulous review now prevents a needless correction later.",
  "your professional reputation is quietly strengthened by current choices.",
  "diplomacy serves you better than directness in one key exchange.",
  "a fresh idea gains traction when grounded in clear next steps.",
  "the day favours those who ask better questions of their work.",
  "a task you have postponed gains momentum the moment you begin it.",
  "clarity about your priorities allows you to decline what does not serve you.",
  "a well-kept promise to a colleague builds capital you will draw on later.",
  "visible progress on a long project restores your sense of purpose.",
  "preparing for a meeting with care makes your voice impossible to ignore.",
  "an offer of help, offered sincerely, strengthens the whole team.",
  "your calm under a shifting situation marks you as someone to trust.",
  "a structured approach converts a vague ambition into a concrete plan.",
  "the competence you quietly demonstrate is being registered accurately.",
  "finishing well is its own reward, and it is noticed more than you think.",
  "a considered objection, raised kindly, protects a plan from a hidden flaw.",
  "taking ownership of an outcome, good or bad, earns lasting respect.",
  "your willingness to learn a new skill distinguishes you from the rest.",
  "a moment of initiative, responsibly taken, opens a useful door.",
  "keeping your word under pressure defines your professional character.",
  "a collaborative spirit multiplies the effect of your own effort.",
  "the work you invest in your craft now returns as confidence later.",
  "an organised inbox frees your mind for the work that actually matters.",
  "steady, visible improvement makes a stronger case than any presentation.",
  "the courage to raise the right question at the right time sets you apart.",
];

export const MONEY_INTRO: readonly string[] = [
  "Financially,",
  "When it comes to money,",
  "On the fiscal front,",
  "In practical matters of money,",
  "Regarding finances,",
  "Where resources are concerned,",
  "In financial matters,",
];

export const MONEY_BODY: readonly string[] = [
  "a measured review of spending brings a reassuring sense of control.",
  "avoiding an impulsive purchase now leaves more room for ease later.",
  "small, consistent habits shape your financial outlook more than any single move.",
  "a budget, even a simple one, transforms anxiety into clarity.",
  "resisting the urge to chase a quick gain protects what you have built.",
  "an unexpected detail in the numbers rewards a second look today.",
  "postponing a major outlay until the picture is clear is a wise stance.",
  "your instinct to save a little more right now is worth heeding.",
  "a planned, deliberate expense can be an investment in your wellbeing.",
  "clarity about your priorities makes saying no easier and lighter.",
  "automating a transfer you keep postponing turns intention into action.",
  "the value of a purchase lies in its use, not its appearance.",
  "financial decisions made calmly now spare you agitation later.",
  "sharing a financial plan with someone you trust adds valuable perspective.",
  "a modest adjustment to your routine frees up more than you expect.",
  "patience with a long-term goal is the strongest position you hold.",
  "avoiding comparison with others keeps your own path in focus.",
  "an organised record simplifies a decision you have been delaying.",
  "spending that reflects your true values feels lighter and wiser.",
  "a conservative choice today becomes a comfort tomorrow.",
  "a regular review of small expenses reveals savings you had overlooked.",
  "renting or borrowing what you rarely use is a quietly intelligent choice.",
  "settling a lingering bill lifts a whisper of background stress.",
  "your resources feel more abundant when you approach them with gratitude.",
  "a clear financial goal transforms vague worry into focused intention.",
  "decluttering possessions you no longer need can also free up cash and clarity.",
  "delaying a purchase by a day reveals whether it is need or habit.",
  "an honest conversation about money removes an unspoken tension.",
  "building an emergency cushion, however slowly, is an act of self-trust.",
  "choosing quality over frequency often proves the more economical path.",
  "your confidence with money grows every time you face the numbers squarely.",
  "a small increase in what you set aside now becomes significant over time.",
  "saying no to one indulgence today keeps your priority intact.",
  "research before a purchase converts impulse into intentional choice.",
  "the peace that follows a disciplined decision is its own return.",
  "a financial fresh start begins with a single honest ledger line.",
  "protecting your resources is an act of care for your future self.",
  "a plan you write down becomes a plan you are far more likely to keep.",
  "recognising when you have enough is the quiet secret of contentment.",
  "turning a financial lesson into a habit honours both your past and future.",
];

export const ENERGY_INTRO: readonly string[] = [
  "On the energy front,",
  "In terms of vitality,",
  "For your energy,",
  "Regarding stamina,",
  "Where your vitality is concerned,",
  "In matters of energy and momentum,",
];

export const ENERGY_BODY: readonly string[] = [
  "your reserves are best guarded by pacing yourself through the busiest hours.",
  "a short pause to breathe resets more than you might think.",
  "movement, however gentle, lifts both body and mood.",
  "honouring rest as a productive act sustains you through the whole cycle.",
  "your focus is strongest in the earlier hours; protect that window.",
  "a deliberate break before you feel depleted preserves your momentum.",
  "hydration and a moment outdoors do more for you than caffeine alone.",
  "the energy you invest in what you love returns to you twofold.",
  "choosing one meaningful task over many leaves you feeling fuller.",
  "your natural rhythm favours consistency over sudden bursts.",
  "listening to your body's signals prevents a needless slowdown.",
  "a lighter morning paves the way for a steadier afternoon.",
  "recharging is not indulgence; it is how you keep showing up.",
  "the pace that sustains interest is the pace that wins the long game.",
  "protection of your mornings means protection of your whole day.",
];

export const ADVICE_INTRO: readonly string[] = [
  "If there is one thing to carry with you,",
  "A quiet note to hold onto:",
  "Consider taking forward this thought:",
  "The heart of the guidance is simple:",
  "Let this be your touchstone:",
  "Worth remembering through the hours ahead:",
];

export const ADVICE_BODY: readonly string[] = [
  "proceed with patience, and let results arrive in their own time.",
  "say the true thing kindly; it will be received better than silence.",
  "return to your own centre before responding to the noise around you.",
  "choose the next right step rather than the grand declaration.",
  "let your words be few and your follow-through complete.",
  "protect your focus the way you would protect something precious.",
  "trust the preparation you have already done and move forward lightly.",
  "be generous with the benefit of the doubt and precise with your facts.",
  "release what you cannot control and attend to what you can.",
  "act from your values and let the outcomes speak for themselves.",
  "offer yourself the same patience you so readily give others.",
  "begin where you are, with what you have, and build from there.",
  "measure progress in direction, not in speed.",
  "let a moment of stillness precede every important answer.",
  "finish what you start, and start only what you mean to finish.",
  "hold your standards high and your expectations gently.",
  "allow belonging to arrive through showing up, not performing.",
  "keep one hand on the plan and one on the present.",
  "lead with curiosity and let certainty follow.",
  "remember that you are allowed to take the longer, kinder road.",
  "tend to the thing you have been quietly avoiding; it holds the key.",
  "choose the response that serves the relationship, not just the argument.",
  "give grace where you have received it, and watch it multiply.",
  "let your energy follow your intention, not the other way around.",
  "protect an hour of quiet for yourself; the day will thank you.",
  "accept help when it is sincerely offered; you need not carry it alone.",
  "let go of the need to win this one; there is more at stake than the point.",
  "move toward the light, even when the full view is not yet clear.",
  "practice the discipline of finishing what you value, in small daily steps.",
  "choose the kind interpretation until the evidence says otherwise.",
  "allow yourself to want what you want without apology.",
  "keep one promise to yourself today; it builds the trust that matters most.",
  "resist the urge to compare your behind-the-scenes to another's highlight reel.",
  "let a paused moment of gratitude reset an anxious habit of thought.",
  "commit to the longer view; the immediate is rarely the whole truth.",
  "give voice to your most honest concern in the gentlest possible way.",
  "allow a plan to bend without breaking your commitment to its aim.",
  "protect your capacity for wonder; it is your secret resource.",
  "choose the door of growth when it quietly opens beside the door of ease.",
  "remember that steadiness, more than brilliance, is what carries you far.",
];

/** Opening lines for the daily "in 30 seconds" overall summary. */
export const GLANCE_OVERALL: readonly string[] = [
  "A day shaped by steady effort rather than sudden turns, with the most rewarding ground close to home and habit.",
  "A day of gentle momentum where attention to detail is rewarded and small steps carry you further than grand plans.",
  "A day favouring clarity and calm; the best outcomes come from doing one thing well rather than many things at once.",
  "A day with a change of rhythm in the air, inviting you to adapt smoothly while keeping your core intentions steady.",
  "A day where connection and follow-through matter most, and progress is built through consistency rather than force.",
  "A day of measured possibility, when patience with a growing process brings the clearest results by evening.",
];

/** "Best for" — the areas or actions the day favours, in plain language. */
export const GLANCE_BEST: Record<string, readonly string[]> = {
  love: [
    "honest conversation and quality time with someone close",
    "expressing appreciation plainly and sharing a genuine feeling",
    "repairing or warming an important relationship through small attentions",
  ],
  work: [
    "finishing an existing task properly rather than starting a new one",
    "careful preparation, clear priorities and steady follow-through",
    "a considered conversation or review that moves a project forward",
  ],
  money: [
    "a calm review of your finances and a small deliberate saving",
    "postponing impulse spending in favour of a clear, planned decision",
    "organising your accounts and settling something you have been putting off",
  ],
  energy: [
    "protecting your rhythm with rest and gentle movement",
    "pacing yourself and guarding the hours when your focus is strongest",
    "honouring your body by matching activity to its natural tempo",
  ],
};

/** "Watch out for" — gentle, non-fearful notes on where to give attention. */
export const GLANCE_WATCH: readonly string[] = [
  "rushing a decision before the full picture is clear",
  "overcommitting your limited energy across too many fronts at once",
  "letting a small assumption grow into a larger misunderstanding",
  "postponing a straightforward conversation that is best had now",
  "measuring your progress against someone else's timeline",
  "loading your day with expectations that leave no room for rest",
];

/** "Best move" — the single practical action to take forward. */
export const GLANCE_MOVE: readonly string[] = [
  "pick one meaningful task and see it through before turning to the next",
  "have the honest conversation you have been circling, kindly and plainly",
  "protect a pocket of quiet time and let your intentions settle there",
  "write down one next step so a vague wish becomes a concrete plan",
  "offer the patience to a situation that you would want shown to you",
  "choose the longer, steadier road over the tempting shortcut",
  "close a small loop you have been meaning to finish, and feel the lift",
];

/** Opening paragraph pools for longer periods. */
export const WEEK_OPENINGS: readonly string[] = [
  "The week ahead rewards a steady hand and a clear sense of what matters most.",
  "This week favours building on what is already in motion over chasing new beginnings.",
  "A measured, intentional week: the gains come from depth, presence and follow-through.",
  "The coming days ask for flexibility and warmth, with room for both focus and ease.",
  "A calmer rhythm settles over the week, encouraging you to work with the season rather than against it.",
];

export const MONTH_OPENINGS: readonly string[] = [
  "This month unfolds around a central theme of steady, deliberate progress across the areas you care about.",
  "The month ahead supports consolidation, honest review and quietly building on what works.",
  "A month for turning attention toward foundations — habits, relationships and resources that hold you steady.",
  "Progress this month comes from patience and consistency, with clarity arriving through action.",
];

export const YEAR_OPENINGS: readonly string[] = [
  "The year ahead is shaped by a drive toward meaningful, sustainable progress in the parts of life you value most.",
  "This year rewards depth over breadth, inviting you to invest in a few things that truly matter and let them grow.",
  "A year of constructive momentum, where steady effort in relationships, work and resources compounds into real change.",
];

/** Short phrasing for an area with no major astrological emphasis today. */
export const NONE_NOTE: readonly string[] = [
  "No major influence today; the ordinary course of things is fine.",
  "Nothing significant to flag today; steady as ever.",
  "Quiet today; no notable pull in this area.",
  "No significant emphasis just now; keep things simple.",
];

export const THEME_SECONDS: Record<Theme, readonly string[]> = {
  love: LOVE_BODY,
  career: CAREER_BODY,
  money: MONEY_BODY,
  energy: ENERGY_BODY,
  relationships: LOVE_BODY,
  growth: [
    "a stretch outside your comfort zone becomes more rewarding than staying put.",
    "learning something new this cycle sharpens a sense of possibility.",
    "an open mind turns an obstacle into a teacher.",
    "asking for feedback now speeds the growth you have been seeking.",
    "each small improvement compounds into something meaningful.",
    "a willingness to revise your view is a quiet form of strength.",
    "curiosity, followed faithfully, leads somewhere genuinely new.",
    "expansion comes from understanding, not from forcing a result.",
    "a book, course, or conversation that stretches you proves worth the effort.",
    "embracing an unfamiliar perspective widens your sense of what is possible.",
    "growth this cycle is less about speed and more about depth.",
    "the lessons you resisted last season arrive now with surprising ease.",
    "a mentor's example reveals a path you had not considered.",
    "your comfort zone expands every time you choose courage over convenience.",
    "reflection on a recent challenge turns experience into wisdom.",
    "a new skill, practised in small daily doses, becomes a lasting asset.",
    "letting a failure teach you rather than define you is a mark of growth.",
    "the willingness to begin again is itself a form of progress.",
    "an open question holds more possibility than a settled answer.",
    "growth favours those who keep returning to the work.",
  ],
  communication: [
    "your words carry more weight now, so choose them with care.",
    "a measured reply preserves a relationship a hasty one could strain.",
    "listening closely reveals what no amount of speaking would uncover.",
    "clear, kind communication opens a door that had been stuck.",
    "putting an idea into words helps it take firm shape.",
    "a well-timed question draws out a truth worth knowing.",
    "writing something down clarifies a thought that felt tangled.",
    "a conversation you have been postponing is best had sooner rather than later.",
    "the tone of your delivery matters as much as the message itself.",
    "confirming you have been understood prevents a costly misunderstanding.",
    "a shared laugh is the fastest route back to ease after tension.",
    "naming a concern plainly, without blame, invites genuine resolution.",
    "your questions today plant seeds for clearer understanding tomorrow.",
    "choosing your words with intention reflects thought for the other person.",
    "a message of appreciation, sent now, will brighten someone's whole day.",
    "pausing before you reply gives your true response room to surface.",
    "saying less and meaning more is a strength right now.",
    "an invitation to collaborate opens a fruitful new thread of exchange.",
  ],
  home: [
    "a small act of thoughtfulness at home settles something long unspoken.",
    "making your space feel cared for returns a quiet sense of peace.",
    "time spent at home renews more than you anticipate.",
    "tending to domestic details clears mental space for bigger things.",
    "the comfort you build at home nourishes everything else.",
    "arranging your surroundings to reflect your values lifts your daily mood.",
    "a simple shared meal draws those you love closer around the table.",
    "creating a corner of calm gives you somewhere to return to.",
    "a household task, done together, turns duty into connection.",
    "honouring the place you live refreshes your sense of belonging.",
    "letting natural light and open space into your home brightens your outlook.",
    "a repair long postponed, finally handled, restores a sense of order.",
    "hosting even one guest with warmth rekindles a sense of welcome.",
    "remembering what made a place feel like home guides your choices now.",
    "the steadiness of home is the foundation you can build everything else on.",
  ],
  creativity: [
    "an idea you have been carrying deserves to be given real form.",
    "allowing yourself to play with a notion, without judgement, frees its potential.",
    "making something, even imperfectly, unlocks a needed sense of flow.",
    "your imagination is a reliable guide when logic runs dry.",
    "a creative detour today feeds the work of the coming weeks.",
    "the blank page holds less fear when you begin with a single mark.",
    "borrowing an idea and making it yours is how all good things evolve.",
    "a walk outdoors often returns with the answer you were chasing.",
    "allowing an unfinished piece to rest lets it ripen on its own.",
    "sharing a rough version invites the collaboration that refines it.",
    "constraint, oddly, is where your most original work emerges.",
    "a creative ritual anchors you even on uninspired days.",
    "collecting fragments of inspiration now builds a rich well to draw from.",
    "your taste is a compass; trust the direction it points.",
    "finishing something imperfect beats abandoning something perfect.",
  ],
  wellbeing: [
    "a gentler routine today supports a steadier week ahead.",
    "small acts of self-care are never wasted; they accumulate.",
    "honouring what your body needs keeps your energy true.",
    "a moment of calm, taken deliberately, reframes everything.",
    "prioritising rest now is the most productive thing you can do.",
    "a mindful breath at a tense moment lowers the temperature of the day.",
    "walking with intention settles a scattered mind.",
    "nourishing food, eaten slowly, is a simple act of self-respect.",
    "scheduling genuine downtime guards against quiet burnout.",
    "a good night's sleep resolves more than any amount of worry.",
    "turning off a screen an hour earlier brightens your mood by morning.",
    "gentle movement releases the tension a busy mind has stored.",
    "being kind to yourself in a hard moment sets the tone for healing.",
    "a check-in with how you are actually feeling is worth your attention.",
    "small sustainable choices beat dramatic habits that cannot last.",
  ],
};
